### ISSUE TITLE
Unexpected black area on a Retina display

### ISSUE THREAD

**Issue by hajimehoshi** [faiface/pixel#1]
https://i.gyazo.com/de4c69df226bab3de1326a02ddabdf5d.png

I executed `go run xor/main.go`. I think this black area is not expected.

**Comment by faiface** [comment]
I pushed a commit that stretches the window content on Hi-DPI displays. Did it fix the problem? The solution is temporary, the pixels will just become 2x larger. Still figuring out how to fix the problem without changing the semantics of the library in major ways.

**Comment by hajimehoshi** [comment]
Yes, this works on macOS!
