### ISSUE TITLE
100% CPU with two windows

### ISSUE THREAD

**Issue by vilterp** [faiface/pixel#100]
Hello, I'm trying to write a program which has two windows. I figured I'd update them in the same loop, like this:

```go
package main

import (
	"time"

	"github.com/faiface/pixel"
	"github.com/faiface/pixel/pixelgl"
)

func run() {
	cfgA := pixelgl.WindowConfig{
		Title:     "A",
		Bounds:    pixel.R(0, 0, 1024, 768),
		Resizable: true,
		VSync:     true,
	}
	winA, err := pixelgl.NewWindow(cfgA)
	if err != nil {
		panic(err)
	}

	cfgB := pixelgl.WindowConfig{
		Title:     "B",
		Bounds:    pixel.R(0, 0, 500, 500),
		Resizable: true,
		VSync:     true,
	}
	winB, err := pixelgl.NewWindow(cfgB)
	if err != nil {
		panic(err)
	}

	fps := time.Tick(time.Second / 60)
	for !winA.Closed() {
		winA.Update()
		winB.Update()

		<-fps
	}
}

func main() {
	pixelgl.Run(run)
}
```

But this has 100% CPU, without even drawing anything. What am I doing wrong? Thanks!

**Comment by faiface** [comment]
I've tested your code on my computer and it doesn't consume 100% CPU (consumes ~5% CPU). How does your code perform with only a single window?

**Comment by vilterp** [comment]
If I comment out `winB.Update()`, it's ~5% CPU.

I'm on macOS 10.13, Go 1.9. Very strange!

**Comment by faiface** [comment]
Try turning off VSync. Maybe your graphics card / graphics driver is doing some nonsense with VSync and 2 windows.

**Comment by vilterp** [comment]
Unfortunately it's still ~100% with VSync off. Are you on a mac? Not sure what other relevant factors could be different between our setups. Thanks for your help!

**Comment by Asday** [comment]
I'm getting the same results on Linux Mint 18, kinda.

Got an 8 logical core CPU, and something is spinning one of the cores to 100%.  With or without vsync, updating the second window as well as the first puts me at ~17% CPU, whereas only updating the first puts me at ~3.5%.

**Comment by faiface** [comment]
Okay, I'm acknowledging that this is a real problem, I'd be really thankful if some of you guys investigated why it happens, because I can't reproduce it.

**Comment by fatlotus** [comment]
I am able to reproduce with 10.13.2 and Go 1.9. I've attached traces from pprof and a sample taken from Activity Monitor.

[profile.pprof.pdf](https://github.com/faiface/pixel/files/1756680/profile.pprof.pdf)
[sample.txt](https://github.com/faiface/pixel/files/1756681/sample.txt)

It looks like the culprit is in `window.go`:

```golang
// Note: must be called inside the main thread.
func (w *Window) begin() {
	if currWin != w {
		w.window.MakeContextCurrent()
		glhf.Init()
		currWin = w
	}
}
```

So every time we switch between two contexts, we need to completely reinitialize the OpenGL context. I guess this must be a pretty heavy operation:

```golang
// Init initializes the OpenGL bindings by loading the function pointers (for
// each OpenGL function) from the active OpenGL context.
//
// It must be called under the presence of an active OpenGL context, e.g.,
// always after calling window.MakeContextCurrent() and always before calling
// any OpenGL functions exported by this package.
//
// On Windows, Init loads pointers that are context-specific (and hence you
// must re-init if switching between OpenGL contexts, although not calling Init
// again after switching between OpenGL contexts may work if the contexts belong
// to the same graphics driver/device).
//
// On macOS and the other POSIX systems, the behavior is different, but code
// written compatible with the Windows behavior is compatible with macOS and the
// other POSIX systems. That is, always Init under an active OpenGL context, and
// always re-init after switching graphics contexts.
//
// For information about caveats of Init, you should read the "Platform Specific
// Function Retrieval" section of https://www.opengl.org/wiki/Load_OpenGL_Functions.
func Init() error {
	return InitWithProcAddrFunc(getProcAddress)
}

// InitWithProcAddrFunc intializes the package using the specified OpenGL
// function pointer loading function. For more cases Init should be used
// instead.
func InitWithProcAddrFunc(getProcAddr func(name string) unsafe.Pointer) error {
	gpActiveShaderProgram = (C.GPACTIVESHADERPROGRAM)(getProcAddr("glActiveShaderProgram"))
	gpActiveTexture = (C.GPACTIVETEXTURE)(getProcAddr("glActiveTexture"))
	if gpActiveTexture == nil {
		return errors.New("glActiveTexture")
	}
	// plus a boatload more getProcAddr syscalls
```

It looks like the slowness comes from reinitializing the context so often:

```bash
% # With both windows active
% go install github.com/fatlotus/pixelb100 && pixelb100
winA.Update() took 23.998276ms
winB.Update() took 19.658762ms
winA.Update() took 24.987797ms
winB.Update() took 22.388975ms
winA.Update() took 36.20775ms
winB.Update() took 18.672262ms
% # With just one window active
% go install github.com/fatlotus/glrepro && glrepro
winA.Update() took 20.70683ms
winA.Update() took 17.545664ms
winA.Update() took 1.824797ms
winA.Update() took 1.404798ms
winA.Update() took 1.251451ms
winA.Update() took 1.600271ms
winA.Update() took 1.30671ms
```

So maybe there's a way to reduce the time required to reinitialize OpenGL for each window?

**Comment by fatlotus** [comment]
Oh, of course: "On Windows, Init loads pointers that are context-specific"... but not on Mac OS X and Linux platforms! In that case, this should be as easy as skipping the call to gl.Init() on POSIX platforms.

Indeed that is what happens. When I apply this patch:
```diff
diff --git a/orphan.go b/orphan.go
index 7e93751..7b8e435 100644
--- a/orphan.go
+++ b/orphan.go
@@ -2,6 +2,8 @@ package glhf
 
 import "github.com/go-gl/gl/v3.3-core/gl"
 
+var ranInit bool = false
+
 // Init initializes OpenGL by loading function pointers from the active OpenGL context.
 // This function must be manually run inside the main thread (using "github.com/faiface/mainthread"
 // package).
@@ -9,9 +11,12 @@ import "github.com/go-gl/gl/v3.3-core/gl"
 // It must be called under the presence of an active OpenGL context, e.g., always after calling
 // window.MakeContextCurrent(). Also, always call this function when switching contexts.
 func Init() {
-       err := gl.Init()
-       if err != nil {
-               panic(err)
+       if !ranInit {
+               err := gl.Init()
+               if err != nil {
+                       panic(err)
+               }
+               ranInit = true
        }
        gl.Enable(gl.BLEND)
        gl.Enable(gl.SCISSOR_TEST)
```

Things perform a bit better:

```bash
% go install github.com/fatlotus/glrepro && glrepro
winA.Update() took 17.005795ms
winB.Update() took 419.011µs
winA.Update() took 2.673347ms
winB.Update() took 394.825µs
winA.Update() took 16.212475ms
winB.Update() took 8.858841ms
winA.Update() took 1.874052ms
winB.Update() took 9.935157ms
winA.Update() took 1.375046ms
winB.Update() took 7.054373ms
winA.Update() took 2.604974ms
winB.Update() took 6.720386ms
winA.Update() took 1.631758ms
winB.Update() took 7.912881ms
winA.Update() took 1.535595ms
winB.Update() took 8.577722ms
```

That still seems pretty slow to me, but at least we're under the 16ms target for 60fps.

**Comment by Asday** [comment]
Doesn't that mean this is still gonna be slow on Windows?

**Comment by faiface** [comment]
Oh, thanks @fatlotus! That's the exact info I needed. The correct place to fix this is not GLHF, though. I pushed a possible fix to a new `two-windows-cpu-usage` branch. Check it out, the fix is very simple (one line away, one line in). The thing is, that for quite a long time now, all windows were sharing the OpenGL context. Therefore, when switching between the windows, initializing OpenGL should be unnecessary. And that's what the fix does, removes the OpenGL initialization from the `win.begin()` method (the one that switches to the window) and puts it only to the `NewWindow` constructor.

Tell me if that works!

**Comment by vilterp** [comment]
On that branch, CPU is around 7% for this example on my machine. This is great, thanks!

**Comment by faiface** [comment]
Excelent! Does it work though? Does drawing on the both of the windows work for you as well?

**Comment by vilterp** [comment]
Yes, both windows draw with low CPU. I say let's merge it :)
