### ISSUE TITLE
Joystick support

### ISSUE THREAD

**Issue by shnifer** [faiface/pixel#101]
Hello! Are you planning to support joystick input in future? I'd be so happy to skip from SDL totally

**Comment by faiface** [comment]
Hi! Joystick is not a very high priority, but GLFW supports joystick, so it's possible. This is a feature I will happily accept if anyone volunteers to implement it.

**Comment by Shnifer** [comment]
Just give me a hint, where to look for in GLHW. I'm very new on github and OS concept, but wanna try to make things better )

**Comment by Shnifer** [comment]
mb useful for someone else, this code seems enough to grab joystick state:
```
var buttons []byte
var axis []float32
if glfw.JoystickPresent(joystick){
	buttons=glfw.GetJoystickButtons(joystick)
	axis=glfw.GetJoystickAxes(joystick)
	fmt.Println(buttons,axis)
}
win.Update()
```

some more may be needed for JustPressedButton

**Comment by faiface** [comment]
Right!
