### ISSUE TITLE
Flickering screen when drawing sprite

### ISSUE THREAD

**Issue by PascalCremer** [faiface/pixel#108]
Thanks for your awesome library!

In my application I want to calculate a single image which takes very long to calculate. It's being rendered pixel by pixel so I would like to show the intermediate output while it's being calculated. My approach has been the following: 

- global `image.ImageRGBA` which is filled by worker thread
- main loop fetches this image, creates a sprite and draws it

**Problem**: I observe heavy flickering using this approach (the image changes rapidly, no screenshot can capture that properly)

![screenshot from 2018-03-28 21 45 57](https://user-images.githubusercontent.com/3254943/38052438-8b96a2a2-32d1-11e8-9cbc-d0617cf52410.png)

It should look like this:

![image](https://user-images.githubusercontent.com/3254943/38052495-afec34aa-32d1-11e8-8d0d-5803e267398b.png)

Here is the code:

```package main

import (
	"github.com/faiface/pixel/pixelgl"
	"github.com/faiface/pixel"
	"image/color"
	"image"
)

func main() {
	pixelgl.Run(run)
}

const width = 800
const height = width

func run() {
	// all of our code will be fired up from here
	cfg := pixelgl.WindowConfig{
		Title:  "Pixel Rocks!",
		Bounds: pixel.R(0, 0, width, height),
		VSync:  true,
	}

	win, _ := pixelgl.NewWindow(cfg)
	c := win.Bounds().Center()

	canvas := image.NewRGBA(image.Rect(0, 0, width, height))

        //  I eventually want to start a goroutine here, but it flickers even without
        // go fillImage(canvas) 
	fillImage(canvas)

	for !win.Closed() {

		win.Clear(color.Black)
		p := pixel.PictureDataFromImage(canvas)

		sprite := pixel.NewSprite(p, p.Bounds())
		sprite.Draw(win, pixel.IM.Moved(c))

		win.Update()
	}
}

func fillImage(canvas *image.RGBA) {
	for x := 0; x < width; x++ {
		for y := 0; y < height; y++ {
                        // heavy computation happens here. Mocked by this simple setter
			canvas.Set(x, y, color.RGBA{uint8(x), uint8(y), 0, 255})
		}
	}
}```

Any help would be much appreciated.

**Comment by faiface** [comment]
Well, let's consider the case when you do spawn a goroutine. You have a race condition there. The `fillImage` function is continuously changing the `canvas` and the main loop will get in the way. `canvas.Set` will be called many times during the call to `pixel.PictureDataFromImage`, which means that different pixels on the screen will be from different versions of the canvas. That might cause the flicker. You need to avoid the race condition, for example with a mutex.

You said that the flicker happens even when you omit the `go` keyword, is that right? If so, what kind of flicker happens? I can't see how any flicker should happen in that situation.

**Comment by PascalCremer** [comment]
Thanks for getting back. I was aware of the race condition you described and should have mentioned that.

As you said, the problem happens even without launching any goroutine. Can you reproduce the problem? The code snipped above should be self-contained. The flicker can be seen in the first screenshot. Part of the image is drawn upon itself with some shift. Note also that the lines are not straight. In real time this happens many times a second, resulting in a flicker.

I also noticed that the flicker doesn't happen if `fillImage(canvas)` is pulled into the main loop. But it don't want to to this because it would not work if I want to fill the image in parallel.

**Comment by faiface** [comment]
Okay man, you found a bug! I just fixed it. The thing was, that the `image` package and Pixel use different coordinate systems (in `image`, the Y-axis is supposed to go up and in Pixel its vice-versa). So what `PictureDataFromImage` does is that it flips the image. Now, when the supplied image is not `*image.RGBA` it copies it into a `*image.RGBA`, flips and converts. But, when the supplied image was `*image.RGBA`, there was an "optimization" that avoided copying the image and thus mutated (flipped) the original image. That was causing the flicker, because the image was flipped around every frame. That should be fixed now.

**Comment by faiface** [comment]
Oh, and btw, it might be better for you to use `pixelgl.Canvas`. It can be readily used as a `Picture` (so no `PictureDataFromImage` conversion is needed, it can be just drawn directly to the screen).

**Comment by PascalCremer** [comment]
Thanks! The problem and gone now. I will also try `pixelgl.Canvas`. :+1:

**Comment by PascalCremer** [comment]
Awesome, using `pixelgl.Canvas` also made my program faster.

**Comment by faiface** [comment]
Glad to hear that! The reason is that `pixelgl.Canvas` data is stored directly on the GPU, whereas when using `*image.RGBA` you need to transfer the data to the GPU over and over each frame.
