### ISSUE TITLE
Very minor change in wiki

### ISSUE THREAD

**Issue by miketmoore** [faiface/pixel#109]
In the following section of the wiki:

https://github.com/faiface/pixel/wiki/Moving,-scaling-and-rotating-with-Matrix#matrix

This 

```
type Matrix [9]float64
```

should now be

```
type Matrix [6]float64
```

according to the source: https://github.com/faiface/pixel/blob/bd5138f4c1ae2a7e5a7ad8bc8988737be38a579b/geometry.go#L328

Thanks!

**Comment by faiface** [comment]
Yeah, you're right, thanks for the catch! Fixed it.
