### ISSUE TITLE
Add text input from window

### ISSUE THREAD

**Issue by faiface** [faiface/pixel#11]
Currently, `*pixelgl.Window` supports checking key and mouse presses. Implementing a user-editable text is close to impossible to do correctly just using this functionality. GLFW library provides a way to correctly get a text input from the user, which depends on their keyboard settings and all that stuff.

Pixel should support this functionality too, through a simple interface. I suggest this single method.
- `(*pixelgl.Window).Typed() string` - returns a string of characters the user typed on the keyboard since the last call to `(*pixelgl.Window).Update`

Note, that the `Typed` method does not and should not handle text deletion. That's easy to implement with `(*pixelgl.Window).Pressed` or `(*pixelgl.Window).JustPressed` method.

**Comment by hajimehoshi** [comment]
How about IME? Will IME be supported?

**Comment by faiface** [comment]
The implementation is going to be pretty straightforward, directly using GLFW's text input capabilities http://www.glfw.org/docs/latest/input_guide.html#input_char . So, if GLFW supports IME, which I think it should, then we'll support it too

**Comment by hajimehoshi** [comment]
I see, but I don't think IME is completely supported by the newest stable glfw (see https://github.com/glfw/glfw/pull/658).

**Comment by faiface** [comment]
I haven't tried it. But I think, that if we really wanted to fully support it, it'd be correct to fix it / fully implement it in GLFW.

**Comment by faiface** [comment]
Or do you have a different approach to this in Ebiten?

**Comment by hajimehoshi** [comment]
No, currently Ebiten doesn't have text-input features, which I want in the future.

**Comment by faiface** [comment]
Just added `Window.Typed` method. No IME support though AFAIK :( .

**Comment by faiface** [comment]
Also, no newlines, which sucks a little bit.
