### ISSUE TITLE
Add function to detect video modes?

### ISSUE THREAD

**Issue by dbriemann** [faiface/pixel#113]
I just toyed around with pixel today and realized that there is no function to detect the screen's supported video modes. For me this feature is kinda essential for a game framework. I know you could just use GLFW to retrieve them and then use the data for pixel.

I think however that this would be a nice feature to have directly integrated into pixel. What is your thought on this? I would be willing to add this and send a pull request if there is interest.

Cheers!

**Comment by faiface** [comment]
Hi!

Yeah, such a contribution would be welcome. I'm not entirely sure why it's not there already, so I guess it's time to fix that.

When you'll work on the PR, keep in mind that we're in Go and you don't have to translate the function's signature literally. Make the API nice and easy to use ;)

Thanks

**Comment by faiface** [comment]
Fixed by #115
