### ISSUE TITLE
Small typo in "Moving, scaling and rotating with Matrix" wiki page

### ISSUE THREAD

**Issue by nimrodshn** [faiface/pixel#115]
It says in the "Moving, scaling and rotating with Matrix" wiki page that `Matrix` represents a 3x3 affine algebraic matrix (see [here](https://github.com/faiface/pixel/wiki/Moving,-scaling-and-rotating-with-Matrix#matrix))  but looking at the implementation its really a 2x3 Matrix : 

```
// Layout is:
// [0] [2] [4]
// [1] [3] [5]
//  0   0   1  (implicit row)
type Matrix [6]float64
```

I would have done a PR for this but since github [doesn't allow for PR's for wiki pages](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github) I opened an issue :cry: 
cc: @faiface @mewmew

**Comment by faiface** [comment]
Yeah, right, I changed the Matrix type definition in the wiki, but forgot this piece of text. Thanks for spotting it! I fixed it.
