### ISSUE TITLE
Run Issue

### ISSUE THREAD

**Issue by lolpakichu** [faiface/pixel#117]
Every time I try to run a program with a pixel library I get this error: 
![screen shot 2018-06-12 at 8 19 33 am](https://user-images.githubusercontent.com/40209289/41299944-6f0accb6-6e19-11e8-9df6-a821f365504f.png)
I don't know how to fix it. Please help!

P.S. This is my code: 
![screen shot 2018-06-12 at 8 21 05 am](https://user-images.githubusercontent.com/40209289/41300016-94ddc6b4-6e19-11e8-952d-4c526399c06b.png)

**Comment by Noofbiz** [comment]
Your $GOPATH is setup weird. You should be able to do just "image/color" and pixel stuff should be "github.com/faiface/pixel", which is where pixel is looking for it inside the library itself. It can't locate it, hence the errors.

**Comment by thegtproject** [comment]
The way you have your gopath setup is indeed the problem. You're treating external packages as standard lib packages and go doesn't like that. There needs to be clear seperation between GOROOT and GOPATH

**Comment by Ilnazz** [comment]
You must install https://github.com/faiface/glhf

**Comment by aprchen** [comment]
The error message is very clear, you need to install those packages . eg: go get -u github.com/faiface/glhf
