### ISSUE TITLE
High CPU and libGL error

### ISSUE THREAD

**Issue by mbndr** [faiface/pixel#121]
I just found this library and began to work through the tutorial but if I create a window the CPU usage is at 100% and I get (VSync on):
```
libGL error: pci id for fd 6: 80ee:beef, driver (null)
libGL error: No driver found
libGL error: failed to load driver: (null)
```
However, the windows is created properly.

When running the examples I can play them (with CPU at 100% and the messages above appear).

This could be a duplicate of #23 
I'm no expert on this topic, but is it possible that the problem is that my Arch Linux instance is running in Virtual Box and the video driver cannot handle some things?

BTW: On the first glance I really like this lib 👍

**Comment by thegtproject** [comment]
Did you try manually limiting the fps as #23 suggested? And yes, I think the issue lies somewhere with the driver or config for some reason ignoring the vsync request.

**Comment by mbndr** [comment]
Ok thanks, that fixes the problem (CPU now about 32% used).
I'll create a PR for mentioning that in the tutorial as @faiface already suggested (https://github.com/faiface/pixel/issues/23#issuecomment-303567938).

**Comment by mbndr** [comment]
@faiface is it possible to add this to the wiki as you suggested (https://github.com/faiface/pixel/issues/23#issuecomment-303567938)?
