### ISSUE TITLE
Icons type?

### ISSUE THREAD

**Issue by d0narnbl1tz** [faiface/pixel#128]
Hi, its me again,

when i want to set an Icon to the game window, it expects
` []pixel.Picture`

but loading an image like showed in the tutorial

`func loadPicture(path string) (pixel.Picture) {
	file, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer file.Close()
	img, _, err := image.Decode(file)
	if err != nil {
		return nil
	}
	return pixel.PictureDataFromImage(img)
}`

returns me 
`pixel.Picture`

as far as i tried the last 2 hours, i can not find any solution how i convert or cast to ` []pixel.Picture`

**Comment by mewmew** [comment]
Try the following

```go
icon := loadPicture("icon.png")
icons := []pixel.Picture{icon}
```

**Comment by d0narnbl1tz** [comment]
@mewmew 
thank you 😄 
it works now 😀
