### ISSUE TITLE
issue on raspberry pi

### ISSUE THREAD

**Issue by kkoralsky** [faiface/pixel#129]
Hi I have following panic on my raspberry pi ver.2 (raspbian stretch) when running w/ opengl driver active:
```
libGL error: MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
panic: creating window failed: VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig
```
i figure this is because pixel specific go-gl  api (v3.2), which raspberrys driver does not implement? Do you think I can use some older pixel release or backport pixelgl to use other api?

**Comment by 20zinnm** [comment]
I had the exact same issue, and I believe it's fixed by switching to the legacy GL driver in Raspbian. However, that gave me horrible performance. It's an issue with the Raspberry Pi's driver for OpenGL, not anything pixel can do/control.

**Comment by 1c3t0rm** [comment]
I'm having the same issue, could you (@20zinnm ) point me in the right way?

**Comment by delp** [comment]
I'm going to close this. If that fix did not work for you, feel free to re-open.
