### ISSUE TITLE
Add support for semantic versioning

### ISSUE THREAD

**Issue by datosh** [faiface/pixel#133]
Hey guys, 

I started to pixel just a few days ago, and I'm having a blast!

There is one problem. The tags you are using do not follow the semantic versioning schema, and therefore do not work well with modules and vgo. Since v0.5.1 is the only version following the schema, I am stuck with that version. Thats fine for now, but I would like to upgrade to v0.7.0 and get the juicy updates :3 
It should be fairly simply to fix.
1. Create additional tags for the old tags that do not follow semantic versioning, i.e., also creating tag v0.7.0 in addition to v0.7
2. For future releases follow the semantic versioning schema for tag names: vX.Y.Z

Fore more information about vgo, modules and semantic versioning you can read. 
https://research.swtch.com/vgo

I'm more than happy to provide help if necessary.
Thanks again for providing such a great library :)

Cheers, 
DaTosh

**Comment by faiface** [comment]
Hey, you're absolutely right! I've added additional tags for each version that wasn't in the semantic versioning format. Check if it works for you!

**Comment by datosh** [comment]
Hey, thanks for providing the new tags.

A simple

```
go mod init <module_name>
go build
```

now correctly pulls version 0.7.0.
Do you think its worth the effort to implement this also for the dependencies of the pixel library? Like mainthread for example.

```
require (
	github.com/faiface/glhf v0.0.0-20170610131041-98c0391c0fd3 // indirect
	github.com/faiface/mainthread v0.0.0-20171120011319-8b78f0a41ae3 // indirect
	github.com/faiface/pixel v0.7.0
	github.com/go-gl/gl v0.0.0-20180407155706-68e253793080 // indirect
	github.com/go-gl/glfw v0.0.0-20180813204114-2484f3e51bc4 // indirect
	github.com/go-gl/mathgl v0.0.0-20180804195959-cdf14b6b8f8a // indirect
	github.com/pkg/errors v0.8.0 // indirect
	golang.org/x/image v0.0.0-20180708004352-c73c2afc3b81
)
```

They currently use @master by default.

**Comment by faiface** [comment]
Well, both `mainthread` and `glhf` don't have any releases, so... And they probably won't really change too much. But if you really feel like it, I can just take their current state and mark it 1.0. Not sure it's worth it though.

**Comment by datosh** [comment]
Seems fair, if it becomes a problem for me in the future I will create an Issue/PR in the respective repo. Thanks for the help!
