### ISSUE TITLE
proposal: split pixel into two repos, pixel and pixel-examples, to reduce size

### ISSUE THREAD

**Issue by mewmew** [faiface/pixel#135]
It has been really great to see the community projects being commited to Pixel, so serve both as example and source of inspiration.

Meanwhile, I have noticed that as of late it takes quite some time to do a fresh git clone of the pixel repo, as it's size has increased from 27 MB at rev 7cff3ce3aed80129b7b1dd57e63439426e11b6ee to 92 MB at rev a9fc26f2616f79db965f250ee3fe3421b3871ab4.

Thus, the suggestion is to split the pixel repo into two repositories, `pixel` and `pixel-examples`, and let only the main library code live in the `pixel` repo.

To do this, we should take precaution to find a way that preserves the original Git history to the extent possible. Any suggestion on how to do this is warmly welcome.

Cheers,
/u

**Comment by Asday** [comment]
I was thinking of making this suggestion on #126, but didn't feel like it was the correct place to...  👍

**Comment by mewmew** [comment]
Current examples repo is at https://github.com/mewspring/pixel-examples, will be merged back into https://github.com/faiface/pixel-examples

**Comment by mewmew** [comment]
Approach used to clean the main repo:

ref: https://dalibornasevic.com/posts/2-permanently-remove-files-and-folders-from-git-repo

```
git filter-branch -f --tree-filter 'rm -rf examples' HEAD
git for-each-ref --format='delete %(refname)' refs/original | git update-ref --stdin
git reflog expire --expire=now --all
git gc --prune=now
```

ref: https://blog.ostermiller.org/git-remove-from-history

```
git filter-branch --tag-name-filter cat --index-filter 'git rm -r --cached --ignore-unmatch examples' --prune-empty -f -- --all
rm -rf .git/refs/original/
git reflog expire --expire=now --all
git gc --aggressive --prune=now
```

Went from 90 MB to 4 MB.

**Comment by mewmew** [comment]
Approach taken to split examples into dedicated repo:

From https://stackoverflow.com/a/17864475
```
cd pixel
git subtree split -P examples -b examples-only
cd ..
mkdir pixel-examples
cd pixel-examples
git init
git pull ../pixel examples-only
```

**Comment by ysmolsky** [comment]
I strongly vote for that.

**Comment by faiface** [comment]
Okay guys, I finally did this. The examples should now reside in the [pixel-examples](https://github.com/faiface/pixel-examples) repo and the main repo should be clean.

Please, check if I did everything alright and if stuff works correctly!

If it does, we can close this issue.

**Comment by faiface** [comment]
I used that approach (both of them, actually), for all branches (not sure if that was necessary).

**Comment by mewmew** [comment]
> I used that approach (both of them, actually), for all branches (not sure if that was necessary).

Strange, when I did a go-get, the repo was 13 MB. And after running the commands in https://github.com/faiface/pixel/issues/135#issuecomment-425983473 the size went to less than 1 MB.

**Comment by faiface** [comment]
```
[faiface@localhost pixel]$ du -hs .git
648K	.git
```

It is less than 1MB on my machine, too.

**Comment by mewmew** [comment]
> It is less than 1MB on my machine, too.

I'll try go-get again.

**Comment by mewmew** [comment]
Good. The repo is less than 1 MB now, I guess it "grows" after download. In either case, the repos have now been split. Thus it's time to close the issue :)
