### ISSUE TITLE
proposal: migrate to glfw 3.3

### ISSUE THREAD

**Issue by ysmolsky** [faiface/pixel#137]
`GLFW 3.2` has a couple of nasty bugs on Mac, for example this: https://github.com/glfw/glfw/issues/1319

Also `GLFW 3.2` was released like 2 years ago.

Is there a plan to migrate to `GLFW 3.3` when it comes out? It looks like `3.3` is 95% ready on the official page.

Thanks!

**Comment by faiface** [comment]
Sure :) As soon as https://github.com/go-gl/glfw adds support for GLFW 3.3, we'll support it too.

**Comment by Chillance** [comment]
Waiting for the https://github.com/go-gl/glfw/tree/3.3-beta to not be a beta I suppose? :)

**Comment by fgrosse** [comment]
Still waiting for go-gl/glfw#219

**Comment by bcvery1** [comment]
GLFW 3.3 finally out: https://github.com/go-gl/glfw/issues/249 :D

**Comment by Chillance** [comment]
Whoho!

**Comment by fgrosse** [comment]
This issue can be closed if #211 is merged :tada: (credits go to @tracer8086)

**Comment by steelx** [comment]
still not merged :(

**Comment by delp** [comment]
Closed by #211 :) :partying_face: :birthday: :tada:
