### ISSUE TITLE
[Question] Save/export display window as image

### ISSUE THREAD

**Issue by psampaz** [faiface/pixel#138]
I found pixel library while searching for a Go library similar to Processing or p5.js. You've done a great job and it seems that pixel can be a good alternative to these libraries for gophers. What I didn't find in the documentation is save/export functionality of the display window to image, something similar to Processing's save function (https://processing.org/reference/save_.html).

Is this somehow supported by pixel?

**Comment by thegtproject** [comment]
Something like this?

```
func Screenshot(win *pixelgl.Window) {
	fmt.Println("taking screenshot...")

	f, err := os.Create("screenshot.png")
	if err != nil {
		panic(err)
	}
	defer f.Close()
	img := pixel.PictureDataFromPicture(win)
	png.Encode(f, img.Image())

	fmt.Println("done")
}
```

**Comment by psampaz** [comment]
Yes exactly this. Thank you very much for this small example.
