### ISSUE TITLE
Rendering under macOS Mojave does not work until window is moved

### ISSUE THREAD

**Issue by peterhellberg** [faiface/pixel#140]
There seem to be a problem with glfw under macOS Mojave: https://github.com/glfw/glfw/issues/1334 
(unfortunately affects Pixel)

I compiled the examples for glfw and this is the result:

#### Before moving window
<img width="640" alt="particles example before moving window" src="https://user-images.githubusercontent.com/565124/46243168-7303a500-c3d1-11e8-83de-8fb5972761c9.png">

#### After moving window
<img width="640" alt="particles example after moving window" src="https://user-images.githubusercontent.com/565124/46243161-523b4f80-c3d1-11e8-8f0c-afd76bd90e1d.png">

The same behavior is seen for code using Pixel.

This issue might also affect Pixel: https://github.com/glfw/glfw/issues/1337

**Comment by peterhellberg** [comment]
An ugly workaround for now is to move the window a single pixel on start, Eg. `win.SetPos(win.GetPos().Add(pixel.V(0, 1)))`

**Comment by peterhellberg** [comment]
The reason for the workaround is to update the `NSOpenGLContext` (and there isn't a direct way to do that)

**Comment by thegtproject** [comment]
I don't use Mac so bare with me, but couldn't you just syscall NSOpenGLContext?

**Comment by peterhellberg** [comment]
Yes, I meant something more along the line of “currently there isn't a direct way to do this from pixel, or go-gl/glfw”

This is the (deprecated) method that needs to be called: https://developer.apple.com/documentation/appkit/nsopenglcontext/1436135-update

In Objective-C this would have been something along these lines: 
```Objective-C
void
cocoa_update_nsgl_context(void* id) {
    NSOpenGLContext *ctx = id;
    [ctx update];
}
```
(copied from https://github.com/kovidgoyal/kitty/blob/b82e74f99ae30599cd88ef6a1216625b57a0414a/kitty/cocoa_window.m#L102-L106)

**Comment by faiface** [comment]
Well, this looks weird (isn't it just some bug in macOS?). But feel free to submit a PR to fix this. And, isn't there a nicer workaround? Like somehow updating the window or something?

**Comment by peterhellberg** [comment]
Yes, this is probably a bug in macOS… but Apple is probably not going to fix something that they (very publicly) have deprecated. Hopefully this can be fixed directly in glfw 3.3

**Comment by peterhellberg** [comment]
The ugly workaround is just a way to trigger `[ctx update]` so to speak.

**Comment by diclophis** [comment]
@peterhellberg I can confirm a similar issue when using this library https://github.com/raysan5/raylib

**Comment by joshua-worby-madefire** [comment]
@peterhellberg I can confirm that we're seeing the same thing on our project for machines that have updated to MacOS 10.14. Any machine that's stayed on MacOS 10.13.6 work fine. 

Also, moving the window does get the rendering to work again.

**Comment by martinlindhe** [comment]
Just adding some (possibly irrelevant) notes to the issue.

SDL2 <= 2.0.8 has a similar issue in Mojave. It has been resolved in the recently released SDL 2.0.9

Here is more info on their issue: https://discourse.libsdl.org/t/macos-10-14-mojave-issues/25060

**Comment by peterhellberg** [comment]
Yes, moving the window (any number of pixels) is a workaround for now.

**Comment by delp** [comment]
@peterhellberg @Lallassu @martinlindhe Anyone want to look at this again now that we are on GLFW 3.3?

**Comment by martinlindhe** [comment]
I think this issue has been resolved for some time by updates to SDL, GLFW and other affected apps.

**Comment by peterhellberg** [comment]
I tried to reproduce the problem but was unable to do so.
