### ISSUE TITLE
Error when executing on Win10

### ISSUE THREAD

**Issue by NGamma** [faiface/pixel#15]
This is what I get when executing the platformer example in Win10. No problem in Ubuntu.

panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.2/glfw.(*Window).SetIcon(0xc0420c2080,
0x682278, 0x0, 0x0)
        C:/gosrc/src/github.com/go-gl/glfw/v3.2/glfw/window.go:353 +0x5b3
github.com/faiface/pixel/pixelgl.NewWindow.func2()
        C:/gosrc/src/github.com/faiface/pixel/pixelgl/window.go:140 +0x4f
github.com/faiface/mainthread.Call.func1()
        C:/gosrc/src/github.com/faiface/mainthread/mainthread.go:64 +0x2d
github.com/faiface/mainthread.Run(0x597da0)
        C:/gosrc/src/github.com/faiface/mainthread/mainthread.go:46 +0x166
github.com/faiface/pixel/pixelgl.Run(0x597da0)
        C:/gosrc/src/github.com/faiface/pixel/pixelgl/run.go:32 +0x65
main.main()
        C:/.../p/main.go:413 +0x34

Any ideas?
Thanks for sharing your library, it's very fun to play with! ^^

**Comment by faiface** [comment]
It's a from a recent feature we added: window icon. When you update the library on Ubuntu (`go get -u ...`) does it still not crash? I believe it should. Anyway, the fix is easy.

**Comment by faiface** [comment]
The bug should be fixed right now. Does it work for you?

**Comment by NGamma** [comment]
Yeah! Perfect! It works now.
