### ISSUE TITLE
How can I remove a sprite?

### ISSUE THREAD

**Issue by RealLau** [faiface/pixel#151]
I'm new to game development, currently I have the code below to detect two sprites collision(I'm not sure it can work perfectly or not, just a simple demo):
```golang
func collision(a pixel.Matrix, b pixel.Matrix, c pixel.Picture, d pixel.Picture) bool {
	w1 := math.Round(c.Bounds().W())
	w2 := math.Round(d.Bounds().W())
	h1 := math.Round(c.Bounds().H())
	h2 := math.Round(d.Bounds().H())
	x1 := a[2]
	y1 := a[5]
	x2 := b[2]
	y2 := b[5]
	return math.Abs((x1+w1/2)-(x2+w2/2)) < math.Abs((w1+w2)/2) && math.Abs((y1+h1/2)-(y2+h2/2)) < math.Abs((h1+h2)/2)
}
```
It works to some extent, but I have a new problem on how to remove a sprite so that I can draw a new image of explosion effect.

**Comment by faiface** [comment]
Hi! I'm not sure I understand. What do you mean by removing a sprite? A sprite has to be drawn with `sprite.Draw(win)` to appear on the screen. If you don't draw it, it doesn't appear, hence it disappears. If you lose a pointer to a sprite, it gets automatically deallocated (removed from memory) by the garbage collector.

**Comment by RealLau** [comment]
OK. Thanks. Will close this issue.
