### ISSUE TITLE
Joystick16 (index 15) is out of bounds

### ISSUE THREAD

**Issue by 20zinnm** [faiface/pixel#155]
According to [the GLFW docs](https://www.glfw.org/docs/latest/group__joysticks.html), we should be able to access Joysticks from index 0-15. However, the following code throws an index out of range error:

```go
package main

import (
	"fmt"
	"github.com/faiface/pixel"
	"github.com/faiface/pixel/pixelgl"
)

func main() {
	pixelgl.Run(run)
}

func run() {
	cfg := pixelgl.WindowConfig{
		Title:     "Joystick Testing",
		Bounds:    pixel.R(0, 0, 1080, 720),
		VSync:     true,
		Resizable: true,
	}
	win, err := pixelgl.NewWindow(cfg)
	defer win.Destroy()
	if err != nil {
		panic(err)
	}
	for joystick := pixelgl.Joystick1; joystick <= pixelgl.Joystick16; joystick++ {
		present := win.JoystickPresent(joystick)
		fmt.Printf("Test whether joystick (index=%d) is present: %v\n", joystick, present)
		if present {
			fmt.Printf("> Name: %s\n", win.JoystickName(joystick))
			buttons := win.JoystickButtonCount(joystick)
			fmt.Printf("> Buttons (%d):\n", buttons)
			for button := 0; button < buttons; button++ {
				fmt.Printf("> > Test whether %d is pressed: %v\n", button, win.JoystickPressed(joystick, button))
			}
		}
	}
}
```

**Comment by faiface** [comment]
@Humpheh I think you forgot to add `+1` in the `joystickState` ;)

**Comment by StephenMichaelis** [comment]
Something should be added to access the variable: glfw.JoystickLast
It returns 15 for me on Ubuntu. It enumerates 1-16 but your system may not use them all.
So you would end up writing something like:
`for joystick := pixelgl.Joystick1; joystick <= win.JoystickLast(); joystick++ { ... }`
If JoystickLast() gets added.
According to : https://www.glfw.org/docs/latest/input_guide.html#joystick

**Comment by 20zinnm** [comment]
Other than that I'm happy to report the joystick API works beautifully for a Gamepad controller.

**Comment by Humpheh** [comment]
Glad to hear that @20zinnm!

**Comment by StephenMichaelis** [comment]
This is not tested code, but something like this off the top of my head, will probably need re-working:
`func (w *Window) JoystickLast() Joystick {
	switch glfw.JoystickLast {
	case 1:
		return Joystick1
	case 2:
		return Joystick2
	case 3:
		return Joystick3
	case 4:
		return Joystick4
	case 5:
		return Joystick5
	case 6:
		return Joystick6
	case 7:
		return Joystick7
	case 8:
		return Joystick8
	case 9:
		return Joystick9
	case 10:
		return Joystick10
	case 11:
		return Joystick11
	case 12:
		return Joystick12
	case 13:
		return Joystick13
	case 14:
		return Joystick14
	case 15:
		return Joystick15
	case 16:
		return Joystick16
	default:
		return Joystick1
	}
}`

**Comment by Humpheh** [comment]
Looking at https://www.glfw.org/docs/latest/group__joysticks.html#ga453edeeabf350827646b6857df4f80ce, it looks like `JoystickLast` will always be set to `Joystick16`?

**Comment by 20zinnm** [comment]
Then GLFW supports all 16 joysticks, since that's the constant, right?

**Comment by StephenMichaelis** [comment]
It supports up to sixteen joysticks, ranging from GLFW_JOYSTICK_1, GLFW_JOYSTICK_2 up to GLFW_JOYSTICK_LAST. 
I take this as meaning GLFW_JOYSTICK_LAST could change depending on the environment.
