### ISSUE TITLE
Would like to help setup cursor stuff and window icons. 

### ISSUE THREAD

**Issue by rucuriousyet** [faiface/pixel#16]
If you aren't currently working on this, I should be able to get this going fairly quickly (I previously wrote XOlib (xolib.com)).

**Comment by faiface** [comment]
Window icons are already done (see #10 and #14). The ability to hide the cursor is also in (see #9 and #13). Do you have anything else in mind?

**Comment by faiface** [comment]
If you eventually come up with something more specific, feel free to open another issue describing what you specifically have in mind. I'm closing this, since the things you mentioned are already done.
