### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by Tobaloidee** [faiface/pixel#166]
Hi @faiface Good day! I am a graphic designer/open source enthusiast and i would like to contribute by offering you a logo design which I think will add more to the project's visibility. It is free and i would be glad to do it of course with your permission.Thanks and best regards! - Tobaloidee

**Comment by faiface** [comment]
Hi @Tobaloidee! My first thought when seeing this was "how can I politely turn him down?", but then I went through your work on [steemit](https://steemit.com/@tobaloidee) and man, I'm impressed!

That being said, I am honored and I'll happily accept a logo from you :)

**Comment by Tobaloidee** [comment]
Thank you for the positive feedback @faiface.  I will do my best for your project and show you the initial draft here as soon as possible. 👍

**Comment by faiface** [comment]
Great, looking forward to that! I'm going to sleep now, so don't be alarmed if I don't respond for several hours :D

**Comment by Tobaloidee** [comment]
Hi @faiface , here's what I came up with..I hope you like it..still open for suggestion
![pixel presentation-01](https://user-images.githubusercontent.com/36028424/54526598-3a24b000-49b2-11e9-879d-00be81b89855.png)
I placed it in light & dark backgrounds to show its usability

**Comment by faiface** [comment]
Thanks for the proposal @Tobaloidee! However, I don't think this one suits the project quite well, for two reasons:

1. The library is called Pixel, but isn't really much about pixelated graphics. It's much more about modern, nice, 2D graphics, possibly with effects and stuff like that. Not that I have anything against retro pixelated graphics, I love many such games and they can be made in Pixel, it's just not its main focus.
2. I'm not a big fan of that light blue color. It seems kinda passive to me. It's perfectly fine for the Go language, but I like to think of the Pixel library as something more... action packed? Colors like red, black, and some wild combinations of colors would suit it better.

As for the content of the design, gopher is fine, but perhaps setting him in some more gaming-related setting, or perhaps getting rid of him completely would be fine too.

Sorry I didn't come forward with these suggestions earlier, would've saved you time.

Thanks for your work, your deliveries are lighting fast ;)

**Comment by Tobaloidee** [comment]
Thanks for the evaluation @faiface I will take note of those and brainstorm again.. :) 👍

**Comment by Tobaloidee** [comment]
![pixen new-01](https://user-images.githubusercontent.com/36028424/54582479-cd5df400-4a4b-11e9-8e03-7e74985b3f03.png)

**Comment by faiface** [comment]
Thanks @Tobaloidee, this is much better! I like both versions, but I'd love to see the second version on a white background (since the README has a white background) and I'd also love to see the first version with some richer, brighter, perhaps lighter colors. I probably prefer the first version, but the colors are a little dull there. After figuring out the colors, I'll definitely make use of it :)

**Comment by Asday** [comment]
Probably worth completely changing the colours on the first one, as those symbols are a [SONY trademark](https://www.playstation.com/en-gb/legal/copyright-and-trademark-notice/).

**Comment by faiface** [comment]
@Asday, aren't they only trademark in that specific arangement as on the website? I'm not an expert on this, so I can't say.

**Comment by Tobaloidee** [comment]
Will change the colors of the first version to avoid any conflicts with trademarks.. :)

**Comment by Asday** [comment]
@faiface I'm not the most expert, but I recall these sorts of things are the reasons no console has the same layout.

Dreamcast:

```
    Green Y
Yellow X   Blue B
    Red A
```

GameCube:

```
    Grey Y
Red B  Green A  Grey X
```

XBox:

```
    Yellow Y
Blue X    Red B
    Green A
```

Playstation:

```
    Green Triangle
Pink Square    Red Circle
    Blue Cross
```

Etc.

**Comment by Tobaloidee** [comment]
![pixel samples-02](https://user-images.githubusercontent.com/36028424/54605908-547b8e00-4a85-11e9-8b36-2159eeaf6506.png)
![pixel samples-03](https://user-images.githubusercontent.com/36028424/54605924-5b0a0580-4a85-11e9-8ef9-54129ac1a2f1.png)

**Comment by faiface** [comment]
@Tobaloidee thanks! But the colors don't really match together here (except in the first one). I'm not trynna be hard on you, really. By matching colors I mean something like http://colormind.io generates. The colors generated there really go well together.

Would you be so kind and put some color variantions like you did already, except that the colors in each of them would go well together? Feel free to use the generator I linked above :D

**Comment by Tobaloidee** [comment]
do you have any particular color palletes in mind? i used palletes there already

**Comment by Tobaloidee** [comment]
![pixel newer sample-02](https://user-images.githubusercontent.com/36028424/54617698-bbf10800-4a9c-11e9-968a-68785961a771.png)
![pixel newer sample-03](https://user-images.githubusercontent.com/36028424/54617705-be536200-4a9c-11e9-9938-7a7bfd191653.png)

**Comment by leragequit** [comment]
https://storage.googleapis.com/golang-assets/Go-brand-book-v1.9.5.pdf this looks like an interesting starting point for color palette, if you want to preserve the association to go.  gopher color is #00add8

**Comment by faiface** [comment]
@Tobaloidee these are good! I'll go with 1c. Thanks alot, you've been great to work with!

**Comment by Tobaloidee** [comment]
You're welcome! @faiface..I will finalize the files earliest tom and make a PR. 👍

**Comment by faiface** [comment]
@Tobaloidee Great, thanks a lot again! Would you please put the files in a new `logos/` folder and if it isn't too much work, would you put there all of the alternatives from your most recent comment here? I might change it around from time to time just for fun :D

**Comment by Tobaloidee** [comment]
you can download all the file formats of the Logo [HERE](https://drive.google.com/drive/u/1/folders/12yULHG-kl53r6AfJk1BTPOaQHHusP1gD) @faiface 

also i created a PR #170 which i uploaded the Logo and updated the Readme file..
Thanks so much for accepting my proposal Sir! Best regards! - tobaloidee

**Comment by faiface** [comment]
Great! Once again, thanks for the great work @Tobaloidee! I'm gonna go merge your PR now.
