### ISSUE TITLE
Intersection detection for lines

### ISSUE THREAD

**Issue by bcvery1** [faiface/pixel#167]
Small feature suggestion: add geometry functions to detect intersection for lines (i.e. vector-to-vector).  Will introduce the following functions:

```go
// IntersectLine returns whether the line formed by going from `from` to `to` intersects the rectangle.
// This includes if it is contained by the rectangle, or is a tangent to one of the rectangles corners or sides.
func (r Rect) IntersectLine(from, to pixel.Vec) bool {}

// IntersectLine returns whether the line formed by going from `from` to `to` intersects the circle.
// This includes if it is contained by the circle, or is a tangent to the circle.
func (c Circle) IntersectLine(from, to pixel.Vec) bool {}

// LinesIntersect returns whether the two lines formed by going from `fromX` to `toX` intersect.
// This includes if one line is on top of the other.
func LinesIntersect(from1, to1, from2, to2 pixel.Vec) bool {}
```

This is a stepping stop to collision detection for n-sided polygons, and rotated rectangles.

*Note: previously you had mentioned you prefer the "intersect" functions to return a vector so calling code can determine minimum vector to prevent collision.  As a line is abstract (e.g. could represent just a line, or could be part of a bigger shape) it maybe clearer to return a boolean. I am willing to concede this point if you'd prefer the higher level of consistency.*

@faiface please let me know what you think.  I'm happy to work on this.

**Comment by faiface** [comment]
That's a great suggestion. Made me think. What if we did it something like this?

1. Have a `Line` struct, which would be just two points: `A` and `B`, or `From`, `To`, whatever.
2. Have a `Line.Intersect(Line) (Point, bool)` method that would also return a point of intersection.
3. Have a `Rect.Lines() []Line` method that would return a list of four lines.

Well, I'm particularly unsure about the third idea. The user could use the lines to check intersections with the rectangle, but it would be a little cumbersome.

If we went with `Line.IntersectRect` instead, the method could return the point of intersection closest to the first point of the line.

Being able to have some point of intersection is pretty useful, for example if you have a laser gun and you want to spark some particles at the point of intersection, or, you just want to cut the laser short there.

Anyway, we need to figure this out, but other than that, this would be extremely helpful and thanks for proposing it :)

**Comment by bcvery1** [comment]
Thanks for the feedback - I'll try make a start on the points you've confirmed, then I can either do two PRs, or adapt the PR when you finalise how you'd like point 3 done

**Comment by faiface** [comment]
Well, which one do you think would be better? To get a list of lines, or to have a pre-made rectangle/line intersection function? Or both?

**Comment by bcvery1** [comment]
I think both.  Currently `Rect` has `IntersectCircle` and `Circle` has `IntersectRect`, so having `IntersectLine` follows that pattern.

*However*, having `Lines` and `Vertices` for `Rect` maybe also useful  for more things than this...?

**Comment by faiface** [comment]
Yeah, that's right!

**Comment by bcvery1** [comment]
Happy to mark this as resolved?

**Comment by faiface** [comment]
Sure :)
