### ISSUE TITLE
Question: 0.9.0 release

### ISSUE THREAD

**Issue by bcvery1** [faiface/pixel#168]
Hey, do you have a set of requirements for the next release?  Are there a specific set of features you want in the library before drafting 0.9.0?

Thanks!

**Comment by faiface** [comment]
Nope, there aren't. There's [this issue](https://github.com/faiface/pixel/issues/46) which I would love to get done at some point, but I never have enough time and dedication to do it :(

**Comment by bcvery1** [comment]
Ah yes, saw that one earlier, definitely an important one!

Thanks for the quick response

**Comment by faiface** [comment]
After that one is done, we could perhaps even release 1.0 :D

**Comment by bcvery1** [comment]
Surely you'd want #18 too, for 1.0.0?

**Comment by faiface** [comment]
Yeah, it would be nice.
