### ISSUE TITLE
I am interested in building a simple 2d gui library based on pixel, thoughts?

### ISSUE THREAD

**Issue by rucuriousyet** [faiface/pixel#17]
I would like to create a gui library based off this one. For the sake of getting people to find it, etc I would like to put this in an organization with Pixel. Thoughts?

**Comment by faiface** [comment]
That would be cool, I'm interested! Pixel currently isn't under any organization, currently it's a repository I own. I'm not planning on changing it yet.

Having said that, if you'd build a GUI based on Pixel of high enough quality, I'd definitely link it in the README or consider creating an organization.

A few questions. What kind of GUI do you have in mind? Retained mode or immediate mode? Immediate mode GUI (IMGUI) might be more useful for games, IMHO. Have you done anything like that in the past?

**Comment by faiface** [comment]
Also, if you'd like it to be kind of an Pixel's "official GUI", I'll definitely give you code reviews ;)

**Comment by faiface** [comment]
However, looking at your code (such as XOLib), I'd suggest you first work on your programming skills for a reasonable time before contributing to anything of the size of Pixel. Creating a GUI app is a great way to improve your skills, however, don't expect that I'll accept your code into Pixel. I might if it ends up being good enough quality. Good luck with that and have a good time ;)

**Comment by rucuriousyet** [comment]
FYI, XOLib was my first or second Go project almost a year ago. I had
originally written it all in another repo and then migrated it to the
current about 8, 4 months ago. I really haven't had the time to work on it
at all since then, but yes its pretty bad code. When I find the time to
work on it again with pixel as the backend Ill let you know. Keep in mind
this code isn't terrible for being new to both OpenGL and Go:
https://github.com/XO-Lib/GCXO/blob/master/Window.go

**Comment by faiface** [comment]
Look, I'll be very glad to accept any of your code if it ends up being good enough. Just saying, that don't have big expectations and focus on improving yourself.

**Comment by rucuriousyet** [comment]
Outside of the occasional lack of idiomatic code, some less than ideal
structures most of what I have public on Github isn't bad code.
Im questioning what you saw that gave you the impression I didn't know how
to code very well.

**Comment by rucuriousyet** [comment]
I usually am, Thx for the tip.

**Comment by faiface** [comment]
Sorry if I offended you, I didn't mean to. I admit I haven't checked all of your code, I mostly checked the XOLib and a few other things (capsule.io, map.io, Geometry), all of which are quite terrible. Looking at some of your newer code, it's a lot better, I admit. Still needs a lot of work, but you're definitely improving.

**Comment by rucuriousyet** [comment]
No worries. I haven't actually written any code for those in quite a while,
but those are not great, as far as some of my more recent stuff you should
checkout message-api or gatekeeper from my spot-app org. Regardless, I'm
sure I do have a ways to go, I am only 17 and just got my first dev job 5
months ago so...

**Comment by faiface** [comment]
I have no doubts in that. I most likely wouldn't approve my own code from 5 years ago. Ok, I'm closing this, since it's just an announcement, but you're welcome to spread a word (either here, or gitter chat) when you'll have something done ;)
