### ISSUE TITLE
Line intersect code is sometimes wrong

### ISSUE THREAD

**Issue by DanTulovsky** [faiface/pixel#175]
Thank you for adding the Lines code.  I believe there is a problem with the intersect code.  The following two test cases show it:

		{
			name:   "Lines intersect",
			fields: fields{A: pixel.V(600, 600), B: pixel.V(925, 150)},
			args:   args{k: pixel.L(pixel.V(740, 255), pixel.V(925, 255))},
			want:   pixel.V(849.1666666666666, 255),
			want1:  true,
		},
		{
			name:   "Lines intersect",
			fields: fields{A: pixel.V(600, 600), B: pixel.V(925, 150)},
			args:   args{k: pixel.L(pixel.V(740, 255), pixel.V(925, 255.0001))},
			want:   pixel.V(849.1666666666666, 255),
			want1:  true,
		},

The second test case fails and returns that the lines do not intersect.  The failure happens in:

	if l.Contains(V(x, y)) && k.Contains(V(x, y)) {
		// The intersect point is on both line segments, they intersect.
		return V(x, y), true
	}

As this functions check fails for the second test case. Both Contains calls return false.  Seems to be a rounding issue:

2019/04/05 12:54:19   closest: Vec(849.1666240490657, 255.00005900898597)
2019/04/05 12:54:19   v: Vec(849.1666240490657, 255.000059008986)

**Comment by faiface** [comment]
@bcvery1 This is for you :)

**Comment by bcvery1** [comment]
No worries, will add these test cases, fix the issue and dig a little deeper in case there are more

Thanks @DanTulovsky for finding this!

**Comment by DanTulovsky** [comment]
fyi, I think relying on floating point numbers being exactly the same in a case like this isn't going to work.  This is what I did for just the intersection part:

// Orientation returns point orientation vs a line
// 0 --> p, q and r are colinear
// 1 --> Clockwise, below
// 2 --> Counterclockwise, above
// From: https://www.geeksforgeeks.org/check-if-two-given-line-segments-intersect/
func Orientation(p, q, r pixel.Vec) int {
	val := (q.Y-p.Y)*(r.X-q.X) - (q.X-p.X)*(r.Y-q.Y)

	switch {
	case val < 0:
		return 2
	case val > 0:
		return 1
	}

	return 0 // collinear
}

// OnSegment Given three collinear points p, q, r, the function checks if
// point q lies on line segment 'pr'
func OnSegment(p, q, r pixel.Vec) bool {
	if q.X <= math.Max(p.X, r.X) && q.X >= math.Min(p.X, r.X) &&
		q.Y <= math.Max(p.Y, r.Y) && q.Y >= math.Min(p.Y, r.Y) {
		return true
	}
	return false
}

// EdgesIntersect returns true if l1 and l2 intersect at any point
func EdgesIntersect(l1, l2 Edge) bool {

	s1 := Orientation(l1.A, l1.B, l2.A)
	s2 := Orientation(l1.A, l1.B, l2.B)
	s3 := Orientation(l2.A, l2.B, l1.A)
	s4 := Orientation(l2.A, l2.B, l1.B)

	if s1 != s2 && s3 != s4 {
		return true
	}

	// colinear
	if s1 == 0 && OnSegment(l1.A, l2.A, l1.B) {
		return true
	}
	if s2 == 0 && OnSegment(l1.A, l2.B, l1.B) {
		return true
	}
	if s3 == 0 && OnSegment(l2.A, l1.A, l2.B) {
		return true
	}
	if s4 == 0 && OnSegment(l2.A, l1.B, l2.B) {
		return true
	}

	return false
}
