### ISSUE TITLE
example doesn't work, especially in sprite

### ISSUE THREAD

**Issue by 0xB4DF4C3D** [faiface/pixel#180]
I'm using Mac mojave 10.14.4. And below is a way I install dependencies
```
 1002  go get github.com/faiface/pixel
 1004  go get -u github.com/go-gl/glfw/v3.2/glfw
 1006  go get github.com/faiface/pixel/pixelgl
```
the leftmost numbers are just history number. don't care about it.

I also ran these example codes in the window 10. At that time, there are no problems.
However when I run the example codes like panda or lights or platformer... They don't work.

Though, maze-generator or typewriter or other examples that don't use any images work well

![image](https://user-images.githubusercontent.com/19762154/56111934-7d177a80-5f94-11e9-86ab-bdf85ba25f37.png)

![image](https://user-images.githubusercontent.com/19762154/56111961-96b8c200-5f94-11e9-996e-c7aaba24bde0.png)

---

This is my first issue. So I might miss out something, then point out it. Thanks :D

**Comment by bcvery1** [comment]
Can reproduce on OSx 10.14.4.  Looks like a recent change has broken it - I'm investigating

**Comment by bcvery1** [comment]
@0xB4DF4C3D @faiface Fix now in PR; a previous PR to remove a redundant loop had set he sprite positioning *before* setting the `Picture` position, so it was incorrect

Ping @Immueggpain :)

**Comment by 0xB4DF4C3D** [comment]
@bcvery1 Wow you awesome!

**Comment by bcvery1** [comment]
@0xB4DF4C3D ...and it's merged - thanks @faiface for the quick merging!

Let me know if this has resolved it for you, it was working fine with the fix on my Mac, so should be good now!

**Comment by faiface** [comment]
Fix merged! I'm sorry @0xB4DF4C3D for merging a bug, I was under the impression that @Immueggpain checked it.
