### ISSUE TITLE
Add text drawing example

### ISSUE THREAD

**Issue by faiface** [faiface/pixel#19]
We need some cool, stunning example demonstrating text drawing capabilities.

**Comment by faiface** [comment]
I was thinking, that perhaps a simplified terminal emulator.

**Comment by faiface** [comment]
Or maybe a simple markdown viewer.

**Comment by ShillyClive** [comment]
Maybe you are already planning on doing this, but I would appreciate it if you could include an example of how to display a line of text and stylize (color, bold, italics, etc) sections of it rather than the whole thing. It is not always simple or obvious how to do so in gaming libraries.

**Comment by faiface** [comment]
@ShillyClive Thanks for the suggestion! A simple markdown viewer would surely demonstrate this functionality, since you can put bold, italic, etc. font anywhere in the markdown text. Do you think that a simple markdown viewer example would be a good idea? (by simple I mean without support for lists, tables, syntax highlighting, etc.)

**Comment by faiface** [comment]
The example is done: [Typewriter](https://github.com/faiface/pixel/tree/master/examples/typewriter)
