### ISSUE TITLE
[Question] Not rendered at first time with `Create window example`

### ISSUE THREAD

**Issue by bokuweb** [faiface/pixel#191]
Hi :) I tried `Create window example`, bit window is not rendered at first time.
However when I move the window, it is rendered.

![drop](https://user-images.githubusercontent.com/10220449/59408306-b7fc2a00-8dee-11e9-95dc-819fa710317c.gif)

Am I missing something?
My machine is MacBook Air (Retina, 13-inch, 2018) OpenGL4.1.

When I move window with `setPos`, it is rendered.

```
	for !win.Closed() {
		pos := win.GetPos()
		pos.X++
		win.SetPos(pos)
		win.Update()
	}
```

**Comment by bcvery1** [comment]
I believe this is a duplicate of #140

**Comment by bokuweb** [comment]
Oops sorry I could not find it.
