### ISSUE TITLE
Windows WIKI updates

### ISSUE THREAD

**Issue by Mudpuppy12** [faiface/pixel#192]
You'll need to add gcc into the path with:
echo 'export PATH=/mingw64/bin:$PATH' >> ~/.bashrc

Also this line:
echo 'export GOPATH=$USERPROFILE/Projects/go' >> ~/.bashrc

should be:
echo 'export GOPATH=$USERPROFILE/go' >> ~/.bashrc

**Comment by faiface** [comment]
Thanks! Fixed.
