### ISSUE TITLE
imdraw's matrix

### ISSUE THREAD

**Issue by Jack-Ji** [faiface/pixel#193]
Hi, I'm trying to learn Pixel recently. I've tried a few matrix(scale, translation) to see the rendering result of imdraw, which didn't change at all, is IMDraw.SetMatrix a redundant method?

Great gamedev framework by the way :-)

**Comment by faiface** [comment]
Hi!

It's not redundant, but you're probably expecting something that it doesn't do :)

Here's from the [docs](https://godoc.org/github.com/faiface/pixel/imdraw#IMDraw.SetMatrix):

> SetMatrix sets a Matrix that all further points will be transformed by.

You set a matrix and everything that you draw to the IMDraw afterwards will be transformed by that matrix.

**Comment by Jack-Ji** [comment]
I see, I misunderstood the IMDraw.Draw and IMDraw.Push, I actually need to SetMatrix before pushing points. Thank you very much!
