### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by fgrosse** [faiface/pixel#194]
I am vendoring pixel via Go modules and would like to use a clean version in my `go.mod` file.
The last release is [v0.8.0][1] from Oct 10, 2018 and I would like to pull in at least the changes from #186 but there are also [plenty of other changes][2] by now.

Can you tag version v0.9.0 so I can update cleanly? :)

Thanks

[1]: https://github.com/faiface/pixel/releases/tag/v0.8.0
[2]: https://github.com/faiface/pixel/compare/v0.8.0...master

**Comment by faiface** [comment]
Right! I'll work on publishing a new release. Hopefully tomorrow or the day after.

**Comment by fgrosse** [comment]
Sure, no stress and reach out if you need a hand 😎

**Comment by faiface** [comment]
Sorry, I haven't been able to find time so far. If you wanna help, you can search through the commits since the last release and find all the new/removed/improved features :D.

**Comment by fgrosse** [comment]
No problem we all have busy lives to attend to 😅

I might find some time this weekend and try to collect a list of features
here in a comment.

Michal Štrba <notifications@github.com> schrieb am Do., 20. Juni 2019,
19:08:

**Comment by faiface** [comment]
That would be very much appreciated :D

**Comment by fgrosse** [comment]
Hey, maybe we can tag a new version after #211 is merged? :)

**Comment by delp** [comment]
Asked this elsewhere but are we incrementing the version according to the [Semantic Versioning](https://semver.org/) standard?

**Comment by fgrosse** [comment]
Yes at least since #195 (it is mentioned at the top of the `CHANGELOG.md` file). I'm not sure though that file was always updated when new things got merged. Maybe you want to doublecheck?

#195 also contains a proposed workflow for updating the changelog which might be useful context for you as new maintainer :+1:

**Comment by delp** [comment]
Thanks, I am finally done moving house so I should be able to spend some time this weekend.

**Comment by fgrosse** [comment]
Looks like v0.9.0 was released yesterday :tada: 

Don't forget to update the [CHANGELOG.md][1] :)

Also of course feel free to close this issue whenever you want

[1]: https://github.com/faiface/pixel/blob/v0.9.0/CHANGELOG.md

**Comment by delp** [comment]
@fgrosse Thanks for watching though, I am hoping for contributors to look over what I'm doing and make sure I'm doing it right // I've not missed anything.

I'm new to working with modules so please reach out if I do something that interferes with your vendoring. Should I close this issue?

**Comment by fgrosse** [comment]
Sure, no problem. I only left the issue open in case you wanted to wait for something else :)
