### ISSUE TITLE
paint specific pixel

### ISSUE THREAD

**Issue by supermuesli** [faiface/pixel#198]
is it possible to paint a pixel at any given coordinate?

**Comment by HymnsForDisco** [comment]
This example uses a pixel buffer, which has its data then loaded into a canvas that is drawn to the window https://github.com/peterhellberg/pixelexperiments/blob/476ad0088448cb8048927fc6211ba6a40fe5f231/particles/particles.go#L76
You can also just draw a rectangle with a size of 1
