### ISSUE TITLE
[Question] Texture Uniforms

### ISSUE THREAD

**Issue by racerxdl** [faiface/pixel#199]
Hi, I was playing a bit with custom shaders in PixelGL and I found an issue: How do I bind a Texture Uniform?

I used for example:
```go
cnv.SetUniform("iChannel0", int32(tex.ID()))
```

But since the Texture is never bound when `Draw` is ran, the custom shader cannot get it. Is there any way I can make the pixelgl.Canvas bind the texture before drawing?

I tried this:

```go
    bind := func() {
        mainthread.Call(func() {
            tex.Begin()
        })
    }
    unbind := func() {
        mainthread.Call(func() {
            tex.End()
        })
    }
       bind()
        iTime = float32(time.Since(startTime).Seconds())
        cnv.Draw(cnv, pixel.IM.Moved(cnv.Bounds().Center()))
        unbind()
```

But it didn't work.

**Comment by racerxdl** [comment]
Just as a reference, if I create a second canvas and set the texture content and then do:

```go
    cnv.SetUniform("iChannel0", int32(0))
```

And then:

```go
     cnv2.Draw(cnv, pixel.IM.Moved(cnv.Bounds().Center()))
```

Then it does the right thing (the texture is passed for iChannel0). But I need to have bit more texture channels there.

**Comment by racerxdl** [comment]
For anyone that wants to do the same, I had to manually create a Renderable GLPicture that uses the GL internals to do the rendering. There is an example here:

https://github.com/racerxdl/gotoyrender/blob/master/toy/toyrender.go

When I have some time I will make a simple tutorial about it.

**Comment by faiface** [comment]
Hey man, thanks for putting this together for other people to see! And sorry for not responding earlier, I was taking a break from GitHub. Anyway, good job!

**Comment by racerxdl** [comment]
No problem! Always great to take a break, just enjoy yours o/

I will make a tutorial next week about it.
