### ISSUE TITLE
Concurrency issues

### ISSUE THREAD

**Issue by CyrusRoshan** [faiface/pixel#200]
Hey! Great project. It seems like I'm having issues with concurrency, though. Is it possible that goroutines run inside the `pixelgl.Run` function block the main UI thread?

I've been having issues preloading/caching files that are displayed as Sprites on the UI, and it seems as if it's because the UI thread is being blocked by the goroutine that's spawned to preload/cache images.

Is this possible?

**Comment by gremour** [comment]
All OpenGL calls should be made from main thread, this is requirement of OpenGL implementation.

If you want to load files in separate goroutines, that's fine. Use channels to pass loaded files to main thread. All pixel (and thus, OpenGL) functions, like PictureDataFromImage have to be called from mainthread, though.

**Comment by CyrusRoshan** [comment]
Ah, I figured this might be the case. Thank you for explaining!
