### ISSUE TITLE
Very bad performance on Raspberry Pi 3

### ISSUE THREAD

**Issue by flagadajones** [faiface/pixel#202]
Hi, I test pixel on RaspberryPI and i get bad performance ~ 8FPS
with a code like this
nothing is draw to screen 
  
        cfg := pixelgl.WindowConfig{
		Title:  "Eye",
		Bounds: pixel.R(0, 0, float64(visage.size.W), float64(visage.size.H)),
	}
	win, err := pixelgl.NewWindow(cfg)
	if err != nil {
		panic(err)
	}
	win.Clear(colornames.Black)
	var (
		frames = 0
		second = time.Tick(time.Second)
	)
	for !win.Closed() {
		win.Update()
		frames++
		select {
		case <-second:
			win.SetTitle(fmt.Sprintf("FPS: %d", frames))
			frames = 0
		default:
		}
	}

if i comment line   win.Update()  FPS jump to 15 000 then it's realy pixel performance problem.
have you an idea how i can solve this ?

**Comment by svera** [comment]
@flagadajones Pixel requires at least OpenGL 3.3, but Raspberry Pi 3 only supports OpenGL 2, so I guess you won't have hardware acceleration and, as everything must be done via software and the RPi CPU is not exactly a strong one , performance will be bad.

**Comment by flagadajones** [comment]
I thanks for this information.  Do you know another module to draw with GO ?  i need to draw ellipse and add mask

**Comment by leragequit** [comment]
you are probably using the software renderer ...

try to enable the experimental opengl support. 
sudo raspi-config -> advanced options -> OpenGL

regards

**Comment by flagadajones** [comment]
@leragequit  i 've tested opengl config in rasp-config  but   i'v got  this error on application start:

>  creating window failed: VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig

**Comment by delp** [comment]
I think this is not something we can address in the library.
