### ISSUE TITLE
How do I resolve this error

### ISSUE THREAD

**Issue by Yakumo-Yukari** [faiface/pixel#221]
# github.com/go-gl/glfw/v3.2/glfw
In file included from ../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20200222043503-6f7a984d4dc4/v3.2/glfw/c_glfw_linbsd.go:24:0:
../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20200222043503-6f7a984d4dc4/v3.2/glfw/glfw/src/linux_joystick.c: In function ‘_glfwInitJoysticksLinux’:
../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20200222043503-6f7a984d4dc4/v3.2/glfw/glfw/src/linux_joystick.c:224:42: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 9 [-Wformat-truncation=]
             snprintf(path, sizeof(path), "%s/%s", dirname, entry->d_name);
                                          ^~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/X11/Xcursor/Xcursor.h:26,
                 from ../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20200222043503-6f7a984d4dc4/v3.2/glfw/glfw/src/x11_platform.h:39,
                 from ../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20200222043503-6f7a984d4dc4/v3.2/glfw/glfw/src/internal.h:169,
                 from ../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20200222043503-6f7a984d4dc4/v3.2/glfw/glfw/src/x11_init.c:28,
                 from ../../pkg/mod/github.com/go-gl/glfw@v0.0.0-20200222043503-6f7a984d4dc4/v3.2/glfw/c_glfw_linbsd.go:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 12 and 267 bytes into a destination of size 20
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# command-line-arguments
./main.go:3:2: imported and not used: "github.com/faiface/pixel"

**Comment by bcvery1** [comment]
@Yakumo-Yukari this looks like you have imported pixel:
```go
import "github.com/faiface/pixel"
```

But then never used it.  Can you upload your `main.go` file?

**Comment by Yakumo-Yukari** [comment]
> @Yakumo-Yukari this looks like you have imported pixel:
> 
> ```go
> import "github.com/faiface/pixel"
> ```
> 
> But then never used it. Can you upload your `main.go` file?

thank you for your help
