### ISSUE TITLE
Fork to a more active repository?

### ISSUE THREAD

**Issue by Chillance** [faiface/pixel#224]
Although I prefer this to stay with @faiface , it might be an idea for anyone to fork it off to be the new official, more active repository? If anyone is willing that is. @faiface seems to be very busy these days, and useful PR's are just waiting to be dealt with.

Thoughts?

Thanks!

**Comment by svera** [comment]
@Chillance more than moving to a new repository I would prefer @faiface to name a new maintainer or maintainers, willing to continue with the awesome work done here. But I agree, it seems that more hands are needed to keep this project alive.

**Comment by faiface** [comment]
You are right guys! Pixel is now looking for a new maintainer, I have opened this issue: https://github.com/faiface/pixel/issues/225

**Comment by Chillance** [comment]
Yeah, maintainer(s) is a better idea.
