### ISSUE TITLE
Use IMDraw to create a shape with a hole

### ISSUE THREAD

**Issue by mr-panta** [faiface/pixel#227]
Hi contributors, 

I'm new for this library and like to know if there is a way to use IMDraw to create a shape with a hole inside like the given images?

![63HcV](https://user-images.githubusercontent.com/5903315/80582312-0b945800-8a41-11ea-9d87-5ef3b2bf76dc.png)
![fillrule-evenodd](https://user-images.githubusercontent.com/5903315/80582315-0d5e1b80-8a41-11ea-989d-c0249bd08ccf.png)
ref: https://stackoverflow.com/questions/3742479/how-to-cut-a-hole-in-an-svg-rectangle

Thank you

**Comment by pentaphobe** [comment]
You could use image masking in a shader, but that's a fairly limiting scenario & doesn't seem like what you want

So - not as far as I'm aware, so you'd have to implement some form of [constructive geometry](https://en.wikipedia.org/wiki/Boolean_operations_on_polygons)

IIRC there are tonnes of implementations of the basic algorithms which would be a breeze to port, try searching for the algorithm names in the above wikipedia article.  Failing that, there may be another library which better suits your needs

**Comment by bcvery1** [comment]
This was mentioned on the discord, but for visibility, check if the `Lights` example provides the functionality you need:
https://github.com/faiface/pixel-examples/tree/master/lights

**Comment by gremour** [comment]
You can draw this as a polygon. Imagine a cut between top left point of rectangle and top left point of triangle. This cut creates 2 more edges and you get closed polygon.

If you need complex things like dynamic hole rotation, this will be more tricky. Boils down to triangulation algorithm.
