### ISSUE TITLE
Tutorial on Matrices: increasing spin rate.

### ISSUE THREAD

**Issue by loeksnokes** [faiface/pixel#228]
I have begun working through your tutorials in preparation to using your graphics library.  It looks like really good fun, and as a plus, I will be able to write the 2D-game my older son asked me for a while back.  Thanks!

On my machine there seems to be an issue:  I am running Windows 10 on an Intel Core i7 Toshiba  Satellite Pro.  I implemented all of the code in your matrices tutorial.  With your code, the gopher spun too fast to see what was going on, but then I noticed it eventually would stop and seem to spin the other direction (it will be clear why later), so I reduced the increment to angle at the end as follows:

	angle := 0.0
	last := time.Now()
	for !win.Closed() {
		dt := time.Since(last).Seconds()
		angle += 0.001 * dt

The gopher now spins slowly enough in the beginning that it is a bit boring, but, a funny thing happens: the gopher slowly and steadily starts to rotate faster and faster.  I thought the point of the thing was to synchronize with frame draw rate so we would get a steady spin?  Now it is clear why it seems the spin was reversing: spinning more than 360 deg looks like a reverse rotation.

Faster and faster rotation means that dt is growing, so what is likely happening is that each frame is taking longer and longer to draw.  I am wondering if this means there is some kind of leak?

**Comment by Asday** [comment]
Could you post your whole code listing?  I just tried to reproduce and was unable to - `3 * dt` produced a steady anticlockwise spin, and `0.001 * dt` was incredibly difficult to see moving, neither appeared to change speed.

**Comment by bcvery1** [comment]
You haven't updated last:
```go
angle := 0.0
last := time.Now()
for !win.Closed() {
	dt := time.Since(last).Seconds()
	last = time.Now()
	angle += 0.001 * dt
```

**Comment by loeksnokes** [comment]
Thanks @bcvery1!

 That was it.  Thanks!  Apologies for not catching it.  I did not see the simple reason as I had another complicated (and wrong) plausible reason in my mind.  I will try not to pester again unless I have lost > 1 day to an issue.
