### ISSUE TITLE
High CPU/GPU usage with VSync on.

### ISSUE THREAD

**Issue by redragonx** [faiface/pixel#23]
Hello,

I'm not sure if this is a bug or a configuration issue somewhere. But anyway, I just found this library and I am following the tutorials provided thus far. One of them suggests to turn on VSync to slow down the update rate so that the code won't be running as fast it can.  Enabling has no effect on my system it seems, it does lock the FPS but doesn't lower the CPU usage/GPU usage. 70% etc 

OS: Arch Linux x64
CPU: Intel i5 2500 3.3 ghz  
GPU: Nvidia GTX 1070

Using latest GLFW, pixel repo code.

How would we debug this?

Thanks!

**Comment by faiface** [comment]
Hi, that's weird.

Does it happen with an idle window?
Does it happen with the examples in the `example` directory?

To debug this, we need to profile the program. To do that, I suggest https://github.com/pkg/profile package. To use, add this line to your `main` function:

```
func main() {
    defer profile.Start().Stop()
    // ...
}
```

The program will produce a profile report file in the `/tmp/` directory. To generate a nice PDF file from it, type this in your terminal:

```
$ go tool pprof -pdf executable_path profile_path > pprof.pdf
```

Where `executable_path` is the compiled Go program that produced the profile file and `profile_path` is the path of the profile file. The produced PDF file contains a nice visualisation and tells which function took the most time. Either try figuring it out yourself, or send the PDF file here somehow.

Alternatively, don't produce a PDF file, but change the `-pdf` flag to a `-txt` flag, which produces a list of functions which took the most CPU time.

**Comment by redragonx** [comment]
```
30.44s of 30.51s total (99.77%)
Dropped 32 nodes (cum <= 0.15s)
      flat  flat%   sum%        cum   cum%
    30.25s 99.15% 99.15%     30.25s 99.15%  runtime.cgocall
     0.19s  0.62% 99.77%      0.19s  0.62%  runtime.usleep
         0     0% 99.77%     30.08s 98.59%  github.com/faiface/glhf.(*Frame).Begin
         0     0% 99.77%     30.08s 98.59%  github.com/faiface/glhf.(*binder).bind
         0     0% 99.77%     30.21s 99.02%  github.com/faiface/mainthread.Run
         0     0% 99.77%     30.07s 98.56%  github.com/faiface/pixel/pixelgl.(*Canvas).Clear.func1
         0     0% 99.77%     30.25s 99.15%  github.com/faiface/pixel/pixelgl.Run
         0     0% 99.77%     30.08s 98.59%  github.com/go-gl/gl/v3.3-core/gl.GetIntegerv
         0     0% 99.77%     30.08s 98.59%  github.com/go-gl/gl/v3.3-core/gl._Cfunc_glowGetIntegerv
         0     0% 99.77%     30.25s 99.15%  main.main
         0     0% 99.77%     30.25s 99.15%  runtime.goexit
         0     0% 99.77%     30.25s 99.15%  runtime.main
         0     0% 99.77%      0.20s  0.66%  runtime.mstart
         0     0% 99.77%      0.20s  0.66%  runtime.mstart1
         0     0% 99.77%      0.20s  0.66%  runtime.sysmon
```

Following the batch tutorial with VSync on

```
7s of 7.07s total (99.01%)
Dropped 20 nodes (cum <= 0.04s)
      flat  flat%   sum%        cum   cum%
        7s 99.01% 99.01%         7s 99.01%  runtime.cgocall
         0     0% 99.01%      6.81s 96.32%  github.com/faiface/glhf.(*Frame).Begin
         0     0% 99.01%      6.81s 96.32%  github.com/faiface/glhf.(*binder).bind
         0     0% 99.01%      6.84s 96.75%  github.com/faiface/mainthread.Call.func1
         0     0% 99.01%      0.12s  1.70%  github.com/faiface/mainthread.CallErr.func1
         0     0% 99.01%      6.96s 98.44%  github.com/faiface/mainthread.Run
         0     0% 99.01%      6.81s 96.32%  github.com/faiface/pixel/pixelgl.(*Window).Update.func2
         0     0% 99.01%      0.12s  1.70%  github.com/faiface/pixel/pixelgl.NewWindow.func1
         0     0% 99.01%         7s 99.01%  github.com/faiface/pixel/pixelgl.Run
         0     0% 99.01%      6.81s 96.32%  github.com/go-gl/gl/v3.3-core/gl.GetIntegerv
         0     0% 99.01%      6.81s 96.32%  github.com/go-gl/gl/v3.3-core/gl._Cfunc_glowGetIntegerv
         0     0% 99.01%      0.10s  1.41%  github.com/go-gl/glfw/v3.2/glfw.CreateWindow
         0     0% 99.01%      0.10s  1.41%  github.com/go-gl/glfw/v3.2/glfw.CreateWindow.func2
         0     0% 99.01%      0.04s  0.57%  github.com/go-gl/glfw/v3.2/glfw.Terminate
         0     0% 99.01%      0.10s  1.41%  github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwCreateWindow
         0     0% 99.01%      0.04s  0.57%  github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwTerminate
         0     0% 99.01%         7s 99.01%  main.main
         0     0% 99.01%      0.04s  0.57%  runtime._ExternalCode
         0     0% 99.01%         7s 99.01%  runtime.goexit
         0     0% 99.01%         7s 99.01%  runtime.main
```
Following the creating window tutorial.

**Comment by faiface** [comment]
Ok, so the numbers tell us that the most CPU time is spent in the C code outside Go which must be the OpenGL code itself. I'm not sure what's causing this, it might be a driver or go-gl issue.

Do you observe the same problems with the examples from the [Ebiten](https://github.com/hajimehoshi/ebiten) library?

**Comment by redragonx** [comment]
Running the lights example works fine with Vsync on. Why is this?

**Comment by faiface** [comment]
The Lights example limits the FPS manually. Perhaps VSync doesn't work for you as intended. Try putting this in your main loop:

```go
fps := time.Tick(time.Second / 60)
for !win.Closed() {
    // ... main loop ...
    win.Update()
    <-fps
}
```

That will wait for the ticker at the end of each frame, thus manually limiting the update rate to 60x per second. Does that change anything?

**Comment by redragonx** [comment]
Yes, this works fine for me.

**Comment by faiface** [comment]
Ok, so that means that enabling VSync on your computer limits the FPS to 60, but doesn't limit the update rate, which is very weird, I don't know how it's even possible. I will definitely mention this in the tutorial.

**Comment by redragonx** [comment]
I can't think of anything special about my system. Just that I am running the CK kernel with Nvidia drivers.

**Comment by faiface** [comment]
Maybe just the driver for your graphics card. Anyway, so that fixed it, right?

**Comment by redragonx** [comment]
Yes, setting the FPS manually works 👍 

Thanks!

**Comment by faiface** [comment]
Great! Will add a note about this to the tutorial later.
