### ISSUE TITLE
Is it possible to draw only part of a sprite?

### ISSUE THREAD

**Issue by karlc1** [faiface/pixel#238]
I have a use case where I would like only part of a sprite to be drawn. What I really want to accomplish is to have a rectangular area in frame where my sprite is only drawn if it is within that area. When it gets close to the edges of the area, I want to calculate which part of the sprite is outside and simply not draw that part. 

I would really like to avoid drawing other objects around the area which my sprite can disappear behind as it would increase the complexity of my code a lot. I have looked at using matrix transformations for this, but cannot figure it out. 

Sorry if there is an obvious answer to this, I have so far only used this lib with Imdraw functions so I'm a bit clueless when it comes to sprites.

**Comment by math2001** [comment]
That's funny, I wanted to do just that today. I hopped to find a function like `win.Clip(rect)` and then `win.Unclip` (which would do exactly what you said: draw only the pixel within that rectangle), but I don't think pixel has such a thing. 

The best way I found was to use a `Canvas` as the filter. The canvas has the size of the rectangle area you talked about, then you render everything you want onto that canvas, and then draw the canvas onto the screen (only the pixel within the bounds of the canvas will be drawn onto the screen). In code, it'd be something like this:

```go
// the coordinates in "screen space" of the clipping rect
canvas := pixelgl.NewCanvas(pixel.R(30, 30, 100, 100))
for !win.Closed() {
	matrix := pixel.IM.Moved(win.Bounds().Center())

	// to render the entire sprite in the middle of the window, you would do this:
	// canvas.Draw(win, matrix)

	// but instead, you render it first onto the canvas. Since we expressed our
	// clipping rect in terms of coordinates in the "screen space" we get to use
	// the exact same matrix
	sprite.Draw(canvas, matrix)

	// now this is the part that took me a while
	// With just pixel.IM, the center of the canvas would be at the origin
	// (bottom left), in other words that's like the anchor. So, you want
	// the anchor at it's original position. And where is the original position?
	// At the canvas's center because we expressed the canvas' coordinates in
	// screen space
	canvas.Draw(win, pixel.IM.Moved(canvas.Bounds().Center()))
}
```

Now, if you want vary your clipping, you don't have to create a new `Canvas` every time, you can  use `SetBounds` to resize it. However, I don't know how expensive that is. From the doc, I'm guessing that it's kind of like a slice in 2d (shrinking just reduces the length, not the capacity, and growing extends the capacity only if required).

Here's a quick example using a clipping rect. Move your mouse around to clip the rendering of the image, and move your mouse out of the window to see the whole picture.

<details>

```go
package main

import (
	"image"
	_ "image/png"
	"os"

	"github.com/faiface/pixel"
	"github.com/faiface/pixel/pixelgl"
	"golang.org/x/image/colornames"
)

func run() {

	win, err := pixelgl.NewWindow(pixelgl.WindowConfig{
		Title:  "pixel is great!",
		Bounds: pixel.R(0, 0, 640, 480),
		VSync:  true,
	})
	if err != nil {
		panic(err)
	}

	f, err := os.Open("/home/math2001/Pictures/22-dec-sun-2019.png")
	if err != nil {
		panic(err)
	}
	img, _, err := image.Decode(f)
	if err != nil {
		panic(err)
	}

	pic := pixel.PictureDataFromImage(img)
	sprite := pixel.NewSprite(pic, pic.Bounds())

	canvas := pixelgl.NewCanvas(pixel.ZR)
	for !win.Closed() {
		win.Clear(colornames.Black)

		matrix := pixel.IM.Moved(win.Bounds().Center())

		if win.MouseInsideWindow() {
			canvas.SetBounds(pixel.R(-100, -100, 100, 100).Moved(win.MousePosition()))
			sprite.Draw(canvas, matrix)
			canvas.Draw(win, pixel.IM.Moved(canvas.Bounds().Center()))
			// canvas.Draw(win, pixel.IM)
		} else {
			sprite.Draw(win, matrix)
		}

		win.Update()
	}

}

func main() {
	pixelgl.Run(run)
}
```

</details>

I'm new around here, so don't take my word for it, there might be a better way... Also, I don't know how hard/valuable it would be implement something like `.DrawClipped` on canvas and sprites.

**Comment by karlc1** [comment]
Thank you, this is a great answer. I believe this is precisely what I need!
