### ISSUE TITLE
help for "nested func" 

### ISSUE THREAD

**Issue by frostways** [faiface/pixel#240]
Hi, thank you for your work and your wiki which is GREAT! (even I would enjoy getting even more of it) 
I'm really new in programming and with pixel I've created a "shoot" function which lets my character shoot, but... I've first created the function inside of the run func... before discovering that go does not let us create nested func... 
So I defined it outside the run function but... I need some variable (such as my main window or things like that ) which are defined inside the run function (so on a local scope... so basically I can't access them)... could you please tell me a way to go through this or tell me if I'm not thinking my code the right way... I've never coded a game before (and almost never coded) 
Thanks you ! <3

**Comment by Asday** [comment]
Pass them as arguments to the function.

https://tour.golang.org/basics/4
