### ISSUE TITLE
How is it with performance ?

### ISSUE THREAD

**Issue by jakubDoka** [faiface/pixel#242]
I decided to lern golang some fun way and find your repository. From the tutorial i managed to render one sprite 1000 times on the screen. Framerate though wos only something around 20 FPS witch makes me wonder is am doing something wrong. I thought am not suppose to render one sprite more then once so ia tried to first make 1000 sprites and then render each once but result wos seemingly same.

**Comment by delp** [comment]
Hey and welcome. I'm glad you're using the library.

It's not really clear what your question or issue is. This doesn't really seem suited to a GitHub Issue but I'm sure there are plenty of folks who would be interested in having this conversation with you on our discord server. 

The link is in the README

Thanks!
