### ISSUE TITLE
Does this 2D library support Chinese characters and Japanese characters

### ISSUE THREAD

**Issue by gakkilove** [faiface/pixel#251]
i have read your code
https://godoc.org/github.com/faiface/pixel/text
i find that it use ASCII，does it support utf8？i mean , i want to print some Chinese characters and Japanese characters
thank you

**Comment by Asday** [comment]
You can make your own atlas with [`NewAtlas`](https://godoc.org/github.com/faiface/pixel/text#NewAtlas), and specify the kanji and hanji you want there.  [`ASCII`](https://godoc.org/github.com/faiface/pixel/text#pkg-variables) and [`Atlas7x13`](https://godoc.org/github.com/faiface/pixel/text#Atlas) appear to be provided for convenience only.

**Comment by gakkilove** [comment]
> You can make your own atlas with [`NewAtlas`](https://godoc.org/github.com/faiface/pixel/text#NewAtlas), and specify the kanji and hanji you want there. [`ASCII`](https://godoc.org/github.com/faiface/pixel/text#pkg-variables) and [`Atlas7x13`](https://godoc.org/github.com/faiface/pixel/text#Atlas) appear to be provided for convenience only.
thank you，I'll try it

**Comment by gakkilove** [comment]
i have sovled this issue with "Microsoft-YaHei.ttf",thank you for your help! @Asday

**Comment by Asday** [comment]
Always a pleasure.
