### ISSUE TITLE
Set Window hints

### ISSUE THREAD

**Issue by Hero9909** [faiface/pixel#261]
im developing a game that makes use of a window in background, where the clicks fall throught and the only control is the cursor. but to get there i need to modify the window hints to something like "undecorated,sticky,below" to keep the window always just above the desktop and below all windows. ive searched to find if i could implement this by myself, but im stuck that im unabled to get a way to set the window hints in glfw. 

it would be absolutly fantastic if someone could implement this or give me a hint what method of glfw this would require

**Comment by cebarks** [comment]
check out https://pkg.go.dev/github.com/go-gl/glfw/v3.3/glfw#WindowHint
for a list of hints: https://pkg.go.dev/github.com/go-gl/glfw/v3.3/glfw#Hint

**Comment by Hero9909** [comment]
hey thx for answering, but ive got not enaught time to build my project futher, ill try your links and will reopen this if i got enaught time again.

ty ayway
