### ISSUE TITLE
func text.NewAtlas() cost too much memory

### ISSUE THREAD

**Issue by gakkilove** [faiface/pixel#274]
I use SourceHanSansK-RegularSub.ttf in my game, so i can print Chinese charactors
here is my code
`fontFaceSourceHan, err := utils.LoadTTF("./resources/font/SourceHanSansK-RegularSub.ttf", 16)`
`utils.PanicIfErr(err)`
`utils.PrintMemoryUsage()`
`SourceHanSansKAtlas = text.NewAtlas(fontFaceSourceHan, text.RangeTable(unicode.Han), text.ASCII)`
`utils.PrintMemoryUsage()`
I find that it costs too much memory and it will cause other problems like frame drop.

![image](https://user-images.githubusercontent.com/24770666/104568163-b067cb80-568a-11eb-81ee-2b3031c2adff.png)

by the way, if i use basicfont.face7x13,it works very well
`text.NewAtlas(basicfont.Face7x13, text.ASCII)`

How can i fix this? 
Thank you very much

**Comment by bcvery1** [comment]
Just wondering, maybe it'll help others debug this, are you creating a new atlas every frame, or just once then reusing it?

**Comment by gakkilove** [comment]
> Just wondering, maybe it'll help others debug this, are you creating a new atlas every frame, or just once then reusing it?

I create this atlas in function init，keep it as a global variable like this
![image](https://user-images.githubusercontent.com/24770666/104677217-ff157400-5723-11eb-8903-cb6b97048bff.png)
I only use text.Text.Clear() and text.WriteString() in every frame
and i have decreased the size of my ttf file, now there are about 3500 chinese charactors in my ttf file,but it still not work well

**Comment by Asday** [comment]
ASCII has way less characters in it that the 3500 you're mentioning - it's possible this is simply expected from loading such a large atlas.

I wonder, back in the day, developers were limited on space not just in memory but also on storage.  Maybe it's worth looking up how developers managed storage of fonts for Chinese game boy games or similar.

For this, I might suggest loading exactly only the characters you're going to use in the near future, maybe deleting and recreating the atlas with different characters at different points in the game.  I won't pretend to know much about Chinese specifically, but generally languages use the most common word/character way more than the second most common, and so on.  It's unlikely you'll need _all_ 3500 characters for every scene throughout your whole game.

**Comment by gakkilove** [comment]
> ASCII has way less characters in it that the 3500 you're mentioning - it's possible this is simply expected from loading such a large atlas.
> 
> I wonder, back in the day, developers were limited on space not just in memory but also on storage. Maybe it's worth looking up how developers managed storage of fonts for Chinese game boy games or similar.
> 
> For this, I might suggest loading exactly only the characters you're going to use in the near future, maybe deleting and recreating the atlas with different characters at different points in the game. I won't pretend to know much about Chinese specifically, but generally languages use the most common word/character way more than the second most common, and so on. It's unlikely you'll need _all_ 3500 characters for every scene throughout your whole game.

Thank you very much for rely this issue. ：）
Actually, i only need about 50 or less characters per scene. i realized it is really stupid to load all 3500 characters into memory,   that's terrible. -_-||
And now, i have changed my code, i  will load those characters which i will use before i get into every scene.
Thank you!
