### ISSUE TITLE
Fragment shader example doc error

### ISSUE THREAD

**Issue by objarni** [faiface/pixel#279]
On this wiki page, the grayscale example does the gopherimg draw call _before_ calling gameloop, which sets the fragment shader program.

I moved the draw call after the SetFragmentShader call in gameloop, and the example worked (rendering was indeed grayscale).

Thanks for an otherwise instructive tutorial! (was the mistake there to intentionally make readers debug/think really hard?? hehe)

https://github.com/faiface/pixel/wiki/Using-a-custom-fragment-shader

**Comment by objarni** [comment]
My updated gameloop:

```golang
func gameloop(win *pixelgl.Window) {
	win.Canvas().SetFragmentShader(fragmentShader)
	gopherimg.Draw(win, pixel.IM.Moved(win.Bounds().Center()))
	for !win.Closed() {
		win.Update()
	}
}
```

**Comment by dusk125** [comment]
This should be resolved now, I updated the wiki to more closely resemble the example by having the gopherimg.Draw call happen in the gameloop loop.
If all looks good, go ahead and close this issue.
Thanks.

**Comment by objarni** [comment]
Not tested but I trust you
