### ISSUE TITLE
pixel-examples needs go.mod for examples to work (PR fixing this is out for review)

### ISSUE THREAD

**Issue by willbeason** [faiface/pixel#280]
Just a friendly prod since pixel-examples doesn't get updated much.

Other users pointed out in [pixel-examples/#17](https://github.com/faiface/pixel-examples/issues/17) that with Go 1.15 module default flags, the examples in the repository no longer work out-of-the-box.  I've created a pull request [pixel-examples/#20](https://github.com/faiface/pixel-examples/pull/20) which resolves the issue.

**Comment by delp** [comment]
Hey @faiface  I don't have permission to modify Pixel-Examples. Would you merge this PR please or grant perms?

**Comment by dusk125** [comment]
The PR has been pulled in, closing.
