### ISSUE TITLE
Move Geometry into its own package

### ISSUE THREAD

**Issue by cebarks** [faiface/pixel#286]
While looking into #277, i noticed the `geometry.go` & `geometry_test.go` files have 1100+ & 1400+ lines each. Maybe this could be refactored out into its own package, and broken up into smaller files (`rectangle.go`, `vec.go`, etc.) to make it easier to maintain down the road not to mention reduce the large amount of functions and types currently exported by the main `github.com/faiface/pixel` package.

**Comment by cebarks** [comment]
This would break existing games, however we aren't fully released yet so its not _**that**_ big of a deal.

**Comment by faiface** [comment]
See my comment on the PR.
