### ISSUE TITLE
Having problems running the example

### ISSUE THREAD

**Issue by elvodqa** [faiface/pixel#294]
I'm trying to run the "creating window" example. But I'm getting compiler errors. And I'm getting similar errors for trying to run go-gl programs. I was using mingw 32 or 64, I'm not sure but I recently reinstalled mingw-64. 

> C:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/mingw/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: Dwarf Error: Can't find .debug_ranges section.
C:\Users\user\AppData\Local\Temp\go-link-945746887\000002.o:c_glfw.cgo2.c:(.text+0xc7e): undefined reference to `__imp__wassert'
C:\Users\user\AppData\Local\Temp\go-link-945746887\000002.o:c_glfw.cgo2.c:(.text+0xe9e): undefined reference to `__imp__wassert'
C:\Users\user\AppData\Local\Temp\go-link-945746887\000002.o:c_glfw.cgo2.c:(.text+0x13d6): undefined reference to `__imp__wassert'
C:\Users\user\AppData\Local\Temp\go-link-945746887\000002.o:c_glfw.cgo2.c:(.text+0x2966): undefined reference to `__imp__wassert'
C:\Users\user\AppData\Local\Temp\go-link-945746887\000002.o:c_glfw.cgo2.c:(.text+0x2b56): undefined reference to `__imp__wassert'
C:\Users\user\AppData\Local\Temp\go-link-945746887\000002.o:c_glfw.cgo2.c:(.text+0x2cf6): more undefined references to `__imp__wassert' follow
collect2.exe: error: ld returned 1 exit status

**Comment by dusk125** [comment]
What's the output for `gcc --version` and `ld --version`

**Comment by dusk125** [comment]
Also I don't know if you followed this or not, but check out our Doc [for getting started with this project on Windows](https://github.com/faiface/pixel/wiki/Building-Pixel-on-Windows).
