### ISSUE TITLE
Doesn't build for me

### ISSUE THREAD

**Issue by natefinch** [faiface/pixel#3]
Running Go 1.8 on linux:

```
$ go get github.com/faiface/pixel/...
# github.com/go-gl/glfw/v3.2/glfw
In file included from ./context.go:4:0:
./glfw/include/GLFW/glfw3.h:171:21: fatal error: GL/gl.h: No such file or directory
compilation terminated.
# github.com/go-gl/gl/v3.3-core/gl
../../../gl/v3.3-core/gl/procaddr.go:52:21: fatal error: GL/glx.h: No such file or directory
compilation terminated.
```

**Comment by natefinch** [comment]
ahh, nevermind, I see in the readme it needs C packages installed.  That's too bad.

**Comment by faiface** [comment]
Looks like you didn't install the required libraries as mentioned in https://github.com/faiface/pixel#requirements
Does that work?

**Comment by faiface** [comment]
Ah, ok, have a good time :)

**Comment by natefinch** [comment]
FWIW, I'd put the requirements above the line about running go get, since I was just going through the instructions in order :)
