### ISSUE TITLE
Sound API Design

### ISSUE THREAD

**Issue by alistanis** [faiface/pixel#30]
@faiface I saw your posts on Reddit and recently switched from a job where I was working on Go full time to where I am now working in Scala/Ruby/Python/Java - so I'm looking for a project to work on outside the DevOps space, and this one caught my attention. I'm a long time game dev enthusiast and I experimented with sound and Go around a year ago, and I was wondering how much thought you'd put into the API design for sound in pixel. If you've already designed something, I'd love to look it over and take a stab at implementing sound for a few platforms - and if not I'd be more than happy to help design an interface.

Let me know!

-Chris

**Comment by faiface** [comment]
Closing this, since the discussion is on the Gitter + my upcoming big audio issue.
