### ISSUE TITLE
Support for Cocoa windows?

### ISSUE THREAD

**Issue by rucuriousyet** [faiface/pixel#31]

**Comment by faiface** [comment]
What do you mean by this? Support for windows under macOS? If so, that's already supported.

**Comment by rucuriousyet** [comment]
I mean to ask if this has support for native cocoa based windows rather
than gflw based windows?

**Comment by faiface** [comment]
GLFW creates native Cocoa windows on OSX, so by using GLFW windows, Pixel is also creating native Cocoa windows.

**Comment by faiface** [comment]
Clear now?

**Comment by faiface** [comment]
I assume my answer was clear enough. Closing, no response from the author.
