### ISSUE TITLE
[Question] Flipping Y-Axis 

### ISSUE THREAD

**Issue by SilbinaryWolf** [faiface/pixel#35]
How do I go about flipping the Y-axis so that:
- Rendering at 0 is at the top of the screen
- Reverse Y (So positive is down and negative is up)

I'd like the code I'm writing to work with however the user has setup their own window too, so being able to set it back would be great.

Aiming to build a little integrated map editor.

**Comment by faiface** [comment]
All you need to do is to set up a correct matrix. So, let's build it up, step-by-step. We start with the identity  matrix.

```go
flipY := pixel.IM
```

Now, we want to flip the Y axis. That can be achieved with scaling by a negative number.

```go
flipY := pixel.IM.ScaledXY(pixel.V(1, -1))
```

The origin is still at the bottom-left though. We need to move it up, to the top-left.

```go
flipY := pixel.IM.ScaledXY(pixel.V(1, -1)).Moved(pixel.V(0, win.Bounds().H()))
```

And that's it. Now, if you want to use a different matrix for camera and you want it to behave as in the world with the flipped axis, all you need to do it this:

```go
win.SetMatrix(cam.Chained(flipY))
```

**Comment by SilbinaryWolf** [comment]
Looks like "pixel.IM.ScaledXY" takes two arguments.
I also don't see much point in flipping manipulating the window matrix if it's just going to require more transformations per sprite I draw...

**Comment by faiface** [comment]
Yep, I forgot that `ScaledXY` also takes an `around` argument, which specifies the point around which you're going to scale it.

Btw, setting the matrix of a window doesn't increase the number of operations per sprite. Creating an individual matrix for each sprite obviously does, but it should be too bad.

If this is a real feature you want to have, this is the way to do it. If it's just about what you're used to, I'd suggest getting used to Pixel's coordinate system ;)

**Comment by faiface** [comment]
I guess the question was answered, so I'm closing. Feel free to reopen if not ;)
