### ISSUE TITLE
Need to install all dependencies by hand

### ISSUE THREAD

**Issue by norbertfuhs** [faiface/pixel#47]
Whe I run go get github.com/faiface/pixel

I have to install all dependencies by hand:
Like 
go get -u github.com/go-gl/glfw/v3.2/glfw
go get github.com/go-gl/mathgl/mgl32
go get golang.org/x/image/colornames
and
go get github.com/faiface/glhf

Isn't there a way that the fist go get install all dependencies automatic?

**Comment by faiface** [comment]
Have you figured it out?

**Comment by norbertfuhs** [comment]
Yes sorry go get -u github.com/faiface/pixel does the trick
