### ISSUE TITLE
imdraw: better line triangulization

### ISSUE THREAD

**Issue by egonelbre** [faiface/pixel#50]
Here's an algorithm that works better for drawing thick lines.

https://github.com/egonelbre/exp/blob/master/pixel/wide-line/main.go#L70

![faiface_pixel_wide-line](https://user-images.githubusercontent.com/192964/29809636-a77f47c6-8ca5-11e7-9acc-f6f458164fe0.png)

Still not ideal, but avoids gaps in outer corners. For solid lines the inner corners don't matter that much.

If you want round corners then in filling corner-gaps part draw a circle segment centered at `a` from `x1` to `a1` with `radius`.

PS: if you find a nice solution for the inner-corners let me know. I haven't yet found a nice solution for cases where you have very thick lines and very tight corners.

**Comment by egonelbre** [comment]
Note: there is a paper on the better one: https://keithp.com/~keithp/talks/cairo2003.pdf, but I haven't yet had chance to implement it.

**Comment by egonelbre** [comment]
This check is an optimization for my own case:

```
if i > 0 && a.Sub(b).Len() < 1 {
	continue
}
```

I didn't want to reduce the number of points before -- for the standard implementation, you probably don't want that check there.

**Comment by faiface** [comment]
Hi, thanks for taking the time! I think you missed something, though. There is an `imd.EndShape` field in `IMDraw` that, I think does what you're talking about. Let me know if I'm right or I missed something. If I'm right, it's maybe a pointer that the API could be improved.

**Comment by egonelbre** [comment]
I tried using them, here's the results I was getting with:

![sharp-end](https://user-images.githubusercontent.com/192964/29811903-ac310b6c-8cad-11e7-8795-03f0c6aacfce.png)
![round-shape](https://user-images.githubusercontent.com/192964/29811904-ad56c888-8cad-11e7-9644-9ef9afeb3b3e.png)

Code looks like:
```
canvas := imdraw.New(nil)
canvas.Color = color.RGBA{0x00, 0x00, 0x00, 0x80}
canvas.EndShape = imdraw.RoundEndShape
{ // internal line
	y := 64.0
	for line := 1.0; line < 64; line *= 2 {
		canvas.Push(
			pixel.V(50, y),
			pixel.V(100, y-16),
			pixel.V(150, y+16),
			pixel.V(200, y-16),
			pixel.V(100, y-64),
		)
		canvas.Line(line)
		y += 80
	}
}
```

**Comment by faiface** [comment]
That's weird, it used to work just fine :D. I'll take a closer look once I get to my computer, if you figure out the bugs before that, let me know!

**Comment by egonelbre** [comment]
Ah, it seems the bug was introduced in f2ef87f1983a3797229d6625cb92f2da7b94d2a4. My best guess is that Normal() rotates in different direction than the previous code.

Documentation says, `u.Normal() == u.Rotated(math.Pi / 2)`, but looks more like `u.Normal() == u.Rotated(-math.Pi / 2)`.

**Comment by egonelbre** [comment]
PS: you may want to take a look at the line-code nevertheless, I think it's easier to follow. :P

**Comment by faiface** [comment]
Right, the normal is wrong, good spot! I can fix it when I'm at my computer, or you can do a PR :).

And yeah, I took the look at the code and it's nice and clear, but an important concern is performance. The main reason why the code in imdraw is not as readable is that it's heavily optimized. If your code can match that performance at least to a reasonable degree, I have no problem replacing it.

**Comment by egonelbre** [comment]
I think it should be on par or faster, but I don't have benchmarks to back up my claims.

It has less special cases, no direct indexing into path (only one for range) and few operations have been merged into one (e.g. Unit().Scaled()) -- possibly avoiding few steps. Of course these perf. improvements highly depends on how well the compiler can optimize the code.

**Comment by faiface** [comment]
`imdraw` package contains benchmarks for all of the drawing operations. You can try replacing the Line code with yours and see how it affects them. Talking about performance aside from asymptotic complexity is usually meaningless without benchmarks :)

**Comment by egonelbre** [comment]
After few fixes to my code here's the comparison:

```
// original
BenchmarkLine/2-8                1000000              1018 ns/op
BenchmarkLine/2-8                2000000               794 ns/op
BenchmarkLine/5-8                 500000              2921 ns/op
BenchmarkLine/5-8                 500000              3359 ns/op
BenchmarkLine/10-8                200000              7159 ns/op
BenchmarkLine/10-8                200000              7370 ns/op
BenchmarkLine/100-8                20000             74132 ns/op
BenchmarkLine/100-8                20000             76393 ns/op
BenchmarkLine/1000-8                2000            726604 ns/op
BenchmarkLine/1000-8                2000            819813 ns/op

// my version
BenchmarkLine/2-8                2000000               821 ns/op
BenchmarkLine/2-8                2000000               837 ns/op
BenchmarkLine/5-8                 500000              2794 ns/op
BenchmarkLine/5-8                 500000              2942 ns/op
BenchmarkLine/10-8                200000              6527 ns/op
BenchmarkLine/10-8                300000              8163 ns/op
BenchmarkLine/100-8                20000             69305 ns/op
BenchmarkLine/100-8                20000             72172 ns/op
BenchmarkLine/1000-8                2000            678756 ns/op
BenchmarkLine/1000-8                2000            726123 ns/op
```

Here's the rough implementation:

```
func (imd *IMDraw) polylineOpen(points []point, radius float64) {
	apoint := points[0]
	var x1, x2, xn pixel.Vec
	for i, bpoint := range points[1:] {
		a, b := apoint.pos, bpoint.pos
		abn := segmentNormal(a, b, radius)
		a1, a2 := a.Add(abn), a.Sub(abn)
		b1, b2 := b.Add(abn), b.Sub(abn)

		// TODO: here you could directly add triangles for quad a1 b1 b2 a2
		imd.pushPt(a1, apoint)
		imd.pushPt(b1, bpoint)
		imd.pushPt(b2, bpoint)
		imd.pushPt(a2, apoint)
		imd.fillPolygon()

		if i > 0 {
			switch bpoint.endshape {
			case NoEndShape:
			case SharpEndShape:
				d := Rotate(xn).Dot(abn)
				if d < 0 {
					_, _, _ = x1, a1, a
				} else {
					_, _, _ = x2, a1, a
				}
			case RoundEndShape:
				// TODO:
				//if d < 0 {
				//	m.Push(x1, a1, a)
				//} else {
				//	m.Push(x2, a2, a)
				//}
			}
		}

		apoint = bpoint
		x1, x2, xn = b1, b2, abn
	}
}
```

Adding the other endshapes will probably make my version a little slower, but... in-essence... on par or slightly faster.

**Comment by faiface** [comment]
Alright, that's better than I expected. If you want to and think it's worth it, I have no problem accepting a PR on this.

**Comment by egonelbre** [comment]
Nah, not a high-priority for me and probably not worth the effort ATM -- I probably should get back to other stuff. I initially thought it was completely missing the code for outer corner endcaps and I had the code lying around, hence converted it to suitable for pixel.

**Comment by faiface** [comment]
Yeah, I agree it's probably not really worth it right now. Thanks anyway.

Anyway, when you have time, any contributions are welcome, either to Pixel, Beep (audio library), or a new experimental, concurrent, pure-software drawing, eventually-no-CGO GUI library.

**Comment by faiface** [comment]
Fixed the normal method.
