### ISSUE TITLE
Cross Compiling

### ISSUE THREAD

**Issue by ghost** [faiface/pixel#53]
When I try to cross compile with

`GOOS=windows GOARCH=386 go build -o main.exe main.go`

I get this error

`../github.com/faiface/glhf/frame.go:7:2: build constraints exclude all Go files in /home/shingtaklam1324/Programming/Go/src/github.com/go-gl/gl/v3.3-core/gl
`

It seems to be a problem with go-gl so is there any way to bypass?

**Comment by faiface** [comment]
PixelGL uses CGO for accessing OpenGL API. There is really no way around this. Now, cross-compiling with CGO is a problem in general.

However, successful cross-compiling has been reported to me when using [XGO](https://github.com/karalabe/xgo), although I have not tried it myself.

**Comment by shingtaklam1324** [comment]
So xgo works Linux->Windows, but is there any dependencies/files that would give an error going Linux/x86 to Linux/ARM(like a raspberry Pi)?

**Comment by faiface** [comment]
You'll have to try for yourself, as I don't have a Raspberry Pi. If you do try, please report if it worked or not!

**Comment by shingtaklam1324** [comment]
I just tried to cross-compile with xgo, which yielded an error with go-gl. So I assume glfw doesn't have proper ARM support atm.

**Comment by quillaja** [comment]
I don't know about cross-compiling specifically, but I got my little project running on both windows 10 and my raspberry pi 3 (through vnc) from the same codebase. After getting all the headers and dependencies out of the way, just doing a `go get` or `go install` worked fine.

My rpi is showing this error, but it's not causing me problems at the moment:
`2017/10/20 10:44:18 PlatformError: X11: RandR gamma ramp support seems broken`

**Comment by mewmew** [comment]
Cross-compiling pixel works great for me.

I'm running Linux on my 64-bit host system, and cross-compile to a Windows 32-bit system.

```
GOOS=windows GOARCH=386 CGO_ENABLED=1 CC=i686-w64-mingw32-gcc go build -o foo.exe foo
```

Note that this requires a cross-compiler to be installed. For Arch Linux, it may easily be installed using pacman:

```
pacman -Sy gcc-multilib mingw-w64-gcc
```

**Comment by peterhellberg** [comment]
@THAAD-Deployment Example of how you can cross compile from macOS to Windows (64-bit):

1. First install a cross compiler:

```sh
brew install mingw-w64
```

2. Build with the `CC` environment variable set to the C-compiler you want to use:

```sh
CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 CGO_ENABLED=1 go build pong-with-sound.go
```

(The code used in the example: [pong-with-sound.go](https://raw.githubusercontent.com/peterhellberg/pixel-experiments/master/pong/pong-with-sound/pong-with-sound.go))

**Comment by quillaja** [comment]
I also was able to cross compile for Win (x64) from Debian 9 (x64) using mingw-64 as @peterhellberg and @mewmew suggested.

**Comment by peterhellberg** [comment]
Should we close this issue?

**Comment by quillaja** [comment]
I think that would be appropriate, especially since it wasn't really an issue with pixel anyway, just the dev environment.

**Comment by faiface** [comment]
Here we go

**Comment by songsen** [comment]
How to linker the C library when cross-compiling with CGO
