### ISSUE TITLE
Port of Box2D

### ISSUE THREAD

**Issue by netgusto** [faiface/pixel#54]
Hello !

I just ported Box2D to go; it's available here : https://github.com/ByteArena/box2d
Thought you might want to know.

**Comment by faiface** [comment]
That's really cool! Sorry, I didn't respond earlier, I'm rather busy these days. Have you thought about (or perhaps did) posting it on Reddit?

**Comment by netgusto** [comment]
Yes, submitted on Reddit, but did not make a wave there :)

**Comment by Chillance** [comment]
This is cool. I think it would help with examples. Maybe make examples using Pixel?

**Comment by netgusto** [comment]
@Chillance it's definitely in our todo list https://github.com/ByteArena/box2d/issues/1
If you have the know how it'd be awesome to PR the first one :D maybe I'm pushing it a bit sorry :)

**Comment by Chillance** [comment]
Yeah, sorry, I'm quite busy with other things at the moment. But if you add examples, it would for sure help you out to get more users. I could be among them, as right now I'm using https://github.com/jakecoffman/cp but would love to see how this would work out instead and then examples helps to get you started to use it.
