### ISSUE TITLE
Do dis pls

### ISSUE THREAD

**Issue by fezjo** [faiface/pixel#55]
1. Rect-Vec

- Clamp

Projection
d) Unit(angle)

Thx

**Comment by faiface** [comment]
d1 thx mf 4 tips u gotem d1 now gtfo lmao

**Comment by fezjo** [comment]
thx & fak u m8 rly gr8ful but d frst 1 not d1 yet so #betterstartworkingyoufag

**Comment by faiface** [comment]
https://www.youtube.com/watch?v=nDd-hLDq9m8

**Comment by fezjo** [comment]
k just dont cum criing when u feel sad

**Comment by Asday** [comment]
... What the hell is going on here? Do you guys know each other in real life or...?

**Comment by fezjo** [comment]
waht?!? no! tahts disgastng! wth? u gay or what!?

**Comment by faiface** [comment]
> Do you guys know each other in real life or...?

Hell yeah.

**Comment by fezjo** [comment]
U know me?! tahts scary sh3t m8, better gtfo here

**Comment by fezjo** [comment]
omg dis dude been editing da sh3t out of my comments wtF
