### ISSUE TITLE
graphics chip too old?

### ISSUE THREAD

**Issue by quillaja** [faiface/pixel#56]
Hi. I'm new to Pixel, but so far I'm loving the ease-of-use and lack of boilerplate! After messing around enough with installing `gcc`, and other related go libraries, I got your "create window" demo to work on my main computer, an Intel NUC with Win 10 and HD Graphics 5000 (which supports OpenGL 4.3).

On my old (>10 yrs) laptop running Win 10 x64 with Mobile Intel 965 graphics (Intel Graphics Media Accelerator X3100, supports only OpenGL 2.0 on windows), I could not get it to work, however. 

I got an error like `WGL: The driver does not appear to support OpenGL`. Sorry, I don't have more info on that because I didn't save the stacktrace or exact error message before proceeding to the next thing. Some searching led me to believe this error message meant that the driver I had did not include OpenGL drivers.

After installing an older version of the drivers the I downloaded from intel.com for this chipset, I got a different error.

    panic: creating window failed: VersionUnavailable: WGL: A forward compatible OpenGL context 
    requested but WGL_ARB_create_context is unavailable
    
    goroutine 5 [running]:
    main.run()
        c:/dev/code/go/src/local/pixdemo/main.go:17 +0x18b
    github.com/faiface/mainthread.Run.func1(0x559cb8, 0xc0420121e0)
        c:/dev/code/go/src/github.com/faiface/mainthread/mainthread.go:39 +0x2e
    created by github.com/faiface/mainthread.Run
        c:/dev/code/go/src/github.com/faiface/mainthread/mainthread.go:38 +0xec

Searching lead me back here, to issue #26 , and makes me believe that I now have OpenGL drivers, but that they're just too old to work with Pixel.

Any confirmation would be appreciated. I don't expect this "issue" to be fixed, since it is probably just the fault of my old computer.

**Comment by Asday** [comment]
If this is the case, could we get a "minimum driver versions" listing in the requirements section of the readme?

**Comment by faiface** [comment]
Hi, you are right, the problem is, that your drivers don't support OpenGL 3.3+, which is the version that Pixel uses. As you found in #26, I've attempted to make Pixel work with OpenGL 2, but it had some problems on macOS, so I dropped that.

I've just added a mention about the minimum OpenGL version, as @Asday suggested, to the README.
