### ISSUE TITLE
Minimizing Windowed/Fullscreen App Causes Panic

### ISSUE THREAD

**Issue by theGeekPirate** [faiface/pixel#58]
OS: Win 10
Go: 1.9

EDIT: This panic is more general than we had imagined, it will occur if you minimize the application in any way (clicking on the minimize icon, Alt+TAB'ing, clicking on the icon on the taskbar), regardless of the windowed/fullscreen state. Comments up until the issue name change imply this is a fullscreen-only issue, which it is not.

If you (for example) make the Platformer example fullscreen then Alt+TAB, it will panic with the following:

```
panic: reflect: slice index out of range

goroutine 1 [running, locked to thread]:
reflect.Value.Index(0x539120, 0xc0423ecd20, 0x97, 0x0, 0x539120, 0x2, 0xc042c09cf8)
        C:/tools/go/src/reflect/value.go:871 +0x1eb
PixelBugTest/vendor/github.com/go-gl/gl/v3.3-core/gl.Ptr(0x539120, 0xc0423ecd20, 0x539120)
        C:/Users/username/go/src/PixelBugTest/vendor/github.com/go-gl/gl/v3.3-core/gl/conversions.go:44 +0xe4
PixelBugTest/vendor/github.com/faiface/glhf.NewTexture(0x0, 0x0, 0x0, 0x691f98, 0x0, 0x0, 0x0)
        C:/Users/username/go/src/PixelBugTest/vendor/github.com/faiface/glhf/texture.go:47 +0x125
PixelBugTest/vendor/github.com/faiface/glhf.NewFrame(0x0, 0x0, 0x0, 0x0)
        C:/Users/username/go/src/PixelBugTest/vendor/github.com/faiface/glhf/frame.go:37 +0x75
PixelBugTest/vendor/github.com/faiface/pixel/pixelgl.(*GLFrame).SetBounds.func1()
        C:/Users/username/go/src/PixelBugTest/vendor/github.com/faiface/pixel/pixelgl/glframe.go:35 +0x8b
PixelBugTest/vendor/github.com/faiface/mainthread.Call.func1()
        C:/Users/username/go/src/PixelBugTest/vendor/github.com/faiface/mainthread/mainthread.go:64 +0x2d
PixelBugTest/vendor/github.com/faiface/mainthread.Run(0x58dbd0)
        C:/Users/username/go/src/PixelBugTest/vendor/github.com/faiface/mainthread/mainthread.go:46 +0xf8
PixelBugTest/vendor/github.com/faiface/pixel/pixelgl.Run(0x58dbd0)
        C:/Users/username/go/src/PixelBugTest/vendor/github.com/faiface/pixel/pixelgl/run.go:32 +0x60
main.main()
        C:/Users/username/go/src/PixelBugTest/vendor/github.com/faiface/pixel/examples/platformer/main.go:394 +0x34
exit status 2
```

The error is possibly occurring in the ```glhf``` library, and I can confirm that it also happens in my personal project.

**Comment by faiface** [comment]
Oh, I somehow missed this issue, noticed it only now, really sorry.

A code which makes it fullscreen would help.

**Comment by theGeekPirate** [comment]
Easiest way would be to add ```Monitor: pixelgl.PrimaryMonitor(),``` to ```pixelgl.WindowConfig{}```:

```
cfg := pixelgl.WindowConfig{
	Title:  "Platformer",
	Monitor: pixelgl.PrimaryMonitor(),
	Bounds: pixel.R(0, 0, 1024, 768),
	VSync:  true,
}
```

**Comment by faiface** [comment]
Interesting. Does not happen to me, fullscreen works just fine. From the error message it seems as if Pixel was trying to create a Window of size 0x0, which crashes. The reason might be that it's detected that the monitor has 0x0 size, which might be because your graphics card is not reporting it correctly? Or something like that, not sure.

**Comment by theGeekPirate** [comment]
I have four monitors, if that helps anything.

The monitors are set up using the Windows UI, and haven't had any issues with anything else, so hopefully that's not the problem.

I'll have some time later on to play around with disconnecting them/changing windows settings to see if I can narrow it down for you.

**Comment by theGeekPirate** [comment]
Also, just making sure that you ALT+TAB'd to attempt to get the error, as your message didn't say anything directly about it—fullscreen works fine otherwise.

**Comment by faiface** [comment]
Yeah, I tried Alt+TABing and it worked fine. But I only have one monitor ATM, will try with multiple monitors later.

**Comment by theGeekPirate** [comment]
I tested it on three separate computers (one connected to a single monitor, another Windows Surface, and my desktop). On my desktop I tried disabling the other monitors via the Windows UI, manually unplugging each of them, and tested each monitor individually (last step probably wasn't necessary, oh well).

Unfortunately, all three experienced the same panic regardless of what I tried =c

**Comment by faiface** [comment]
Related issue: #63

**Comment by faiface** [comment]
Ok, I tried even minimizing the Windows, but even that works fine for me. Some more investigation on this issue is needed. Doesn't pressing Alt+TAB somehow trigger minimizing too @theGeekPirate ? Because in #63 it happens on minimizing.

**Comment by theGeekPirate** [comment]
I don't know the specifics of how Windows handles it, but yes, it's the act of minimizing which causes the issue.

For instance, I can do the same thing by simply clicking away to a separate monitor (which I believe would also minimize the fullscreen platformer game, in this example).

**Comment by theGeekPirate** [comment]
Since you guys are investigating GPUs, I may as well add that I'm using an NVIDIA 1060 on my desktop, an NVIDIA 480GTX on my living room computer, and the Intel HD Graphics on my Windows Surface.

**Comment by xinkiknix** [comment]
The function call creating the error is  `func (gf *GLFrame) SetBounds(bounds pixel.Rect)`
bounds has w & h = 0
on line 34 it calls 	`gf.frame = glhf.NewFrame(w, h, false)`
with w & h both = 0 (which is invalid)
From mainthread.go the SetBounds function is called from within function f() which is the Run function...Debugging that is rather difficult 
```
func Call(f func()) {
	checkRun()
	callQueue <- func() {
		f()
		respChan <- struct{}{}
	}
	<-respChan
}
```
Switching from fullscreen to windowed view using `win.SetMonitor(nil)` does not create an error.

with this code I switch between fullscreen and windowed, only the fullscreen craches when **alt-tab**-ed
```
for !win.Closed() {

		if win.JustPressed(pixelgl.KeySpace) {
			win.SetMonitor(nil)
		}
		if win.JustPressed(pixelgl.KeyKPEnter) {
			win.SetMonitor(pixelgl.PrimaryMonitor())
		}
		batch.Draw(win)
		win.Update()
	}
```

**Comment by theGeekPirate** [comment]
@xinkiknix It's the act of minimizing which causes the issue, and when you hit Alt+TAB on a windowed application, it doesn't minimize it, so it doesn't cause an issue \^_^

One the other hand, if you simply click on the "minimize" button on the windowed application, you will experience the same panic.

Good info though!

**Comment by faiface** [comment]
I submitted a quick fix to the `master` (because the fix is harmless for other purposes). The fix simply avoids allocating a 0x0 frame.

I'd love you guys to test it out, because I suspect that this problem has deeper roots and quick-fixing it this way will reveal another side-problem with the thing. But if not, I'm happy.

**Comment by theGeekPirate** [comment]
@faiface Fixed on my end for both fullscreen and windowed applications, thanks!

**Comment by faiface** [comment]
That's good news. I expected the window would end up somehow wrong when going back from the minimized state, but that's probably not happening, so that's good. I'll hear from @xinkiknix and then close this issue, if there's no problems.

**Comment by theGeekPirate** [comment]
I should have mentioned that I also tested bringing them back up, so we're good there =)

**Comment by xinkiknix** [comment]
Works for me also (Win 7 and Win 10)

**Comment by xinkiknix** [comment]
See: https://github.com/hemantasapkota/go-convexhull/blob/master/main.go
in 
`func onResize(w, h int) {
	if h == 0 {
		h = 1
}
gl.Viewport(0, 0, w, h)
...`
they seem to have exactly the same issue, and solve it the same way, might be a **OpenGL** feature....

**Comment by faiface** [comment]
I guess this should've been closed long ago, closing now.

**Comment by xinkiknix** [comment]
Indeed, works as expected now, and similar to other implementations
