### ISSUE TITLE
pixelgl.Window bounds and position

### ISSUE THREAD

**Issue by Schobers** [faiface/pixel#60]
I've noticed that Window.SetBounds() doesn't change the position currently. I'd propose to change the behaviour of SetBounds() so it does change the position of the window. Additionally I'd add a SetSize() (or Resize()) that does change the size only (the current behaviour of SetBounds()). At last I'd make it explicit for now that the Min property of the Window.bounds property isn't used (and set it to zero by default).

Proposed implementation: Schobers/pixel@2b985c01869f58213b84fa1a6d40f0390d23706d

**Comment by faiface** [comment]
Hi! `Window.SetBounds` doesn't change the "physical position" of the window (which could be a useful feature, potentially, not sure), but it **does** change the `Min` value of the `Window.Bounds` rectangle. If that's not the case, then that's a bug.

**Comment by Schobers** [comment]
It does indeed, but it's not completely clear to me why or when Window.bounds is updated.

**Comment by faiface** [comment]
Okay, I understand that. The behaviour is as follows:
1. `Window.SetBounds` sets `Window.Bounds` to the provided rectangle. The physical size of the window is changed to the size of the provided rectangle, but the physical position remains.
2. Moving a windows does nothing to `Window.Bounds`.
3. Resizing a window changes the `Max` value of `Window.Bounds` according to the resizing. `Min` value remains unaffected.

`Window.Bounds` is a rectangle where `Min` can be different from `(0, 0)`. Sometimes it's useful. For example, when you want to have `(0, 0)` at the center of the screen, instead of the bottom-left corner.

Maybe I should explain this behaviour better in the doc? Or are you still proposing changes?

**Comment by Schobers** [comment]
Ok, I didn't consider the usefulness of changing the view. In that case I'd keep it simple and a Window.Move/SetPos.

**Comment by Schobers** [comment]
Related to that I'd also add Maximize, Iconify and Restore to Window (see Schobers/pixel@e35cd40d7997acfb48f89a72736375ec28410c54)

**Comment by faiface** [comment]
Yeah, `Window.SetPos` is a good idea. Since the user can query the size of the screen (`pixelgl.Monitor`), it's sufficient for positioning the window to the center of the screen.

I will be able to get to implement this not sooner than Sunday. If you feel like it, a PR would be great!

**Comment by faiface** [comment]
I'm not so sure about `Maximize`, `Iconify` and `Restore`, because I feel like it should only be the ability of the user to do that. I usually hate it when programs do that on their own :D

**Comment by Schobers** [comment]
I've only got use cases for Maximize actually but for consistency in the API (with regards to glfw.Window) I proposed all three of them. The use case for Maximize was having a splash screen followed by maximized window when started (without creating a new window). Additionally it could be usefull for the first run (when the user didn't resize the window yet).

**Comment by faiface** [comment]
Wouldn't fullscreen be more appropriate in such cases than maximize?

**Comment by Schobers** [comment]
Well, for a game it would, for desktop applications not really (sure, I'm aware this is actually a game library :)).

**Comment by faiface** [comment]
Are you planning on using Pixel to develop desktop apps?

**Comment by Schobers** [comment]
Yes, singular for now, since there is a lot of overlap between a 2D game and a desktop application.

**Comment by faiface** [comment]
Okay, I understand, although I'm still not convinced about the overall usefulness versus the API complication and the possibilities of misuse. And yeah, Pixel is primarily a game library.

I'd postpone a decision about these functions until later, and only add them if there's a bigger demand for them. But I'm perfectly fine with `Window.SetPos`/`Window.SetPosition`.

**Comment by faiface** [comment]
Ok, thanks for the PR, I guess this issue can be closed now?

**Comment by Schobers** [comment]
Thanks for the pull.
