### ISSUE TITLE
Custom shaders - post processing

### ISSUE THREAD

**Issue by yanlipnican** [faiface/pixel#62]
Is there any way in current state of library to use custom shader? For example draw images on canvas and use custom shader to postprocess image?

**Comment by faiface** [comment]
It is possible but it's not particularly easy right now. What you would need to do is to create an own `pixel.Target` implementation, something like `pixelgl.Canvas` but with your own shader. You could basically just copy `pixelgl.Canvas`, but replace the shader.

This should be way easier in the future, although I don't have much time to work on Pixel at the moment.

**Comment by yanlipnican** [comment]
I would probably also need custom ```canvasTriangles``` so i can pass cutom data to shader.

**Comment by faiface** [comment]
Yeah, that's right.

**Comment by faiface** [comment]
If you encounter any problems with that, feel free to ask.
