### ISSUE TITLE
Clicking on icon in taskbar creates error

### ISSUE THREAD

**Issue by Manny102030** [faiface/pixel#63]
I have pixel on Windows 10 and go 1.9.1 64 bit. I'm new to Go and GitHub so there might be a simple solution that I missed. I was playing around and found that I could add icons to my applications, so I got a random .png and used it. It worked fine for the most part, but when I click on the application icon or minimize the window in the task-bar it immediately closes and creates an error. 

My Code:
```go
func PictureFromImage(path string) (pixel.Picture) {
    file, err := os.Open(path)
    if err != nil {
        fmt.Println()
        return nil
    }

    img, _, err := image.Decode(file)
    if err != nil {
        fmt.Println(err)
        return nil
    }

    defer file.Close() // Make sure file closes after function returns

    return pixel.PictureDataFromImage(img)
}

func run() {

    // Load window Icon
    // It is a slice because WindowConfig only takes a slice
    icons := make([]pixel.Picture, 1)
    img := PictureFromImage("icon.png")
    icons[0] = img

    cfg := pixelgl.WindowConfig{
            Title: "Window",
            Icon: icons,
            Bounds: pixel.R(0, 0, 800, 600),
            VSync: true,
    }

    window, err := pixelgl.NewWindow(cfg)
    if err != nil {
        panic(err)
    }


    for !window.Closed() {
        window.Clear(colornames.Black)

        window.Update()
    }
}
```

Which produces the error: 
`panic: reflect: slice index out of range`

I don't think there was a mistake in my code, because it was mostly copied off of the tutorials (like the PictureFromImage function). I think it might be because I only gave 1 image in the slice, but the comments in the WindowConfig struct in window.go say that it's ok if I pass only 1.

**Comment by faiface** [comment]
Related issue: #58

**Comment by faiface** [comment]
Hi, in the related issue, the same behaviour happens on pressing Alt+TAB. Is that your case too?

**Comment by Manny102030** [comment]
I checked the related issue, and we both got the exact same error, word for word. I used the platformer example he used and added `Resizable: true`, but ALT+TAB doesn't do anything. I tried all the other examples too, and ALT+TAB didn't do anything but minimizing or pressing the icon created the error. I noticed that you said it could be an error in the gpu, and in the lights demo you said your computer can't handle it so I think the reason why you can't recreate the error is because we're using gpus. I'll try recreating the error with my cpu instead and see if it works.

**Comment by theGeekPirate** [comment]
Can confirm—any type of minimizing (whether windowed or fullscreen) will cause this panic.
