### ISSUE TITLE
text.Clear() 

### ISSUE THREAD

**Issue by xinkiknix** [faiface/pixel#65]
When using txt.Clear() in the for !win.Closed() {} loop and write some text afterwards no text is shown. Clear should only remove the text, not clear the whole instance? I had to replace txt.Clear() with txt := text.New(pixel.V(20, 50), atlas) in the loop to make it work as intended.

**Comment by faiface** [comment]
`txt.Clear` followed by moving `txt.Dot` to `txt.Orig` is equivalent to creating a new `Text` object (except much faster), so you must be doing something wrong. I believe you are not moving `txt.Dot` to its original place, or something else.

**Comment by xinkiknix** [comment]
Indeed then I must be doing something wrong, what is the correct implementation then for txt.Clear?
I tried your recommendation but the text does not remain visible, I am updating the text in each frame.

Thanks

**Comment by xinkiknix** [comment]
Problem fixed.
