### ISSUE TITLE
Polygon()

### ISSUE THREAD

**Issue by xinkiknix** [faiface/pixel#71]
When I use `.Polygon(0)` (e.g. fill) and have a complex figure the fill does not just fill the area but also (on the left side?) it colors outside the lines...
When switching to `.Polygon(1)` I have the correct figure, but the lines are not crisp, it seems the line thickness is perpendicular  with the actual line. Now the lines seems "hairy" when I zoom in.

Is there a way to only fill the designated area defined by a closed set of points?

**Comment by faiface** [comment]
Hi, thanks for the issue. Could you, please, submit some screenshots demonstrating what you're talking about, so that I can understand better? Thanks.

**Comment by xinkiknix** [comment]
Please check:
`// imdtst
package main

import (
	"math"

	"github.com/faiface/pixel"
	"github.com/faiface/pixel/imdraw"
	"github.com/faiface/pixel/pixelgl"
	"golang.org/x/image/colornames"
)

var imd, imd2, imd3 *imdraw.IMDraw

func run() {
	var (
		//lastposition = pixel.ZV
		//camPos = pixel.ZV
		//camSpeed     = 10.0
		camZoom      = 1.0
		camZoomSpeed = 1.2
		//currCamZoom  = 1.0
	)
	cfg := pixelgl.WindowConfig{
		Title:  "Pixel Imd test",
		Bounds: pixel.R(0, 0, 1500, 1000),
		VSync:  true,
	}
	win, _ := pixelgl.NewWindow(cfg)
	imd = imd2
	for !win.Closed() {
		mousePos := win.MousePosition()
		camZoom *= math.Pow(camZoomSpeed, win.MouseScroll().Y)
		cam := pixel.IM.Scaled(mousePos, camZoom)
		win.SetMatrix(cam)
		if win.JustPressed(pixelgl.KeyEscape) {
			return
		}
		if win.JustPressed(pixelgl.KeySpace) {
			if imd == imd2 {
				imd = imd3
			} else {
				imd = imd2
			}
		}

		win.Clear(colornames.Aliceblue)
		imd.Draw(win)
		win.Update()
	}
}
func main() {
	italie := []pixel.Vec{
		pixel.V(541.57, 771.64),
		pixel.V(541.86, 771.56),
		pixel.V(542.28, 771.56),
		pixel.V(542.78, 771.73),
		pixel.V(543.47, 771.78),
		pixel.V(544.15, 771.99),
		pixel.V(544.31, 771.97),
		pixel.V(544.78, 771.84),
		pixel.V(545.09, 771.85),
		pixel.V(545.79, 772.03),
		pixel.V(545.99, 772.22),
		pixel.V(546.49, 772.51),
		pixel.V(547.31, 773.61),
		pixel.V(547.38, 773.94),
		pixel.V(547.46, 774.12),
		pixel.V(547.60, 774.15),
		pixel.V(547.91, 774.09),
		pixel.V(547.94, 773.15),
		pixel.V(548.21, 772.87),
		pixel.V(548.87, 772.60),
		pixel.V(549.38, 772.47),
		pixel.V(549.67, 772.09),
		pixel.V(549.79, 771.78),
		pixel.V(549.65, 771.49),
		pixel.V(549.64, 771.33),
		pixel.V(549.92, 771.25),
		pixel.V(550.31, 771.29),
		pixel.V(550.45, 771.37),
		pixel.V(550.48, 771.48),
		pixel.V(550.43, 771.58),
		pixel.V(550.15, 771.77),
		pixel.V(550.11, 771.85),
		pixel.V(550.87, 772.77),
		pixel.V(551.33, 773.14),
		pixel.V(551.45, 773.50),
		pixel.V(551.64, 773.58),
		pixel.V(552.34, 773.59),
		pixel.V(552.61, 773.34),
		pixel.V(553.11, 773.34),
		pixel.V(553.36, 773.45),
		pixel.V(553.79, 773.76),
		pixel.V(554.00, 773.76),
		pixel.V(554.30, 773.64),
		pixel.V(554.38, 773.40),
		pixel.V(554.74, 773.30),
		pixel.V(554.87, 773.13),
		pixel.V(555.11, 773.11),
		pixel.V(555.35, 773.20),
		pixel.V(555.35, 773.24),
		pixel.V(555.10, 773.44),
		pixel.V(555.11, 773.80),
		pixel.V(554.77, 774.13),
		pixel.V(554.78, 774.40),
		pixel.V(554.97, 774.53),
		pixel.V(555.22, 774.59),
		pixel.V(555.60, 774.60),
		pixel.V(555.65, 774.37),
		pixel.V(555.80, 774.31),
		pixel.V(555.96, 774.31),
		pixel.V(556.32, 774.42),
		pixel.V(556.48, 774.52),
		pixel.V(556.49, 774.61),
		pixel.V(556.25, 775.06),
		pixel.V(556.28, 775.36),
		pixel.V(556.62, 775.71),
		pixel.V(556.85, 775.83),
		pixel.V(556.93, 775.85),
		pixel.V(557.14, 775.88),
		pixel.V(557.75, 775.51),
		pixel.V(558.42, 775.36),
		pixel.V(558.85, 775.41),
		pixel.V(558.96, 775.51),
		pixel.V(559.46, 776.19),
		pixel.V(559.71, 776.33),
		pixel.V(559.94, 776.36),
		pixel.V(560.54, 776.34),
		pixel.V(561.17, 776.59),
		pixel.V(561.74, 776.28),
		pixel.V(561.97, 776.28),
		pixel.V(562.85, 776.53),
		pixel.V(563.20, 776.64),
		pixel.V(563.40, 776.78),
		pixel.V(563.55, 776.79),
		pixel.V(563.65, 776.66),
		pixel.V(563.67, 776.40),
		pixel.V(564.00, 776.13),
		pixel.V(564.34, 776.07),
		pixel.V(564.50, 775.96),
		pixel.V(564.56, 775.72),
		pixel.V(565.30, 775.27),
		pixel.V(565.91, 775.14),
		pixel.V(566.32, 775.10),
		pixel.V(567.07, 774.91),
		pixel.V(569.61, 774.68),
		pixel.V(570.52, 774.65),
		pixel.V(571.29, 774.53),
		pixel.V(570.98, 774.41),
		pixel.V(570.49, 774.41),
		pixel.V(570.00, 774.25),
		pixel.V(569.92, 774.16),
		pixel.V(569.40, 773.80),
		pixel.V(569.30, 773.57),
		pixel.V(569.40, 773.34),
		pixel.V(569.65, 773.22),
		pixel.V(569.92, 773.20),
		pixel.V(570.14, 773.10),
		pixel.V(570.18, 772.97),
		pixel.V(569.84, 772.66),
		pixel.V(569.56, 772.52),
		pixel.V(569.53, 772.35),
		pixel.V(569.63, 772.28),
		pixel.V(569.89, 772.30),
		pixel.V(570.10, 772.25),
		pixel.V(570.38, 772.01),
		pixel.V(570.42, 771.65),
		pixel.V(570.65, 771.32),
		pixel.V(571.24, 770.86),
		pixel.V(571.41, 770.64),
		pixel.V(571.24, 770.38),
		pixel.V(570.89, 770.24),
		pixel.V(570.38, 770.25),
		pixel.V(570.02, 770.30),
		pixel.V(570.08, 770.34),
		pixel.V(570.24, 770.36),
		pixel.V(570.77, 770.34),
		pixel.V(570.86, 770.49),
		pixel.V(570.40, 770.79),
		pixel.V(570.32, 770.99),
		pixel.V(570.27, 771.25),
		pixel.V(570.05, 771.50),
		pixel.V(569.83, 771.59),
		pixel.V(569.69, 771.62),
		pixel.V(569.56, 771.57),
		pixel.V(569.46, 771.35),
		pixel.V(569.37, 771.29),
		pixel.V(569.18, 771.30),
		pixel.V(568.99, 771.26),
		pixel.V(568.82, 771.22),
		pixel.V(568.68, 771.22),
		pixel.V(568.24, 771.36),
		pixel.V(567.85, 771.45),
		pixel.V(567.59, 771.42),
		pixel.V(567.48, 771.35),
		pixel.V(567.47, 771.23),
		pixel.V(567.60, 771.09),
		pixel.V(567.81, 770.97),
		pixel.V(567.81, 770.91),
		pixel.V(567.81, 770.82),
		pixel.V(567.58, 770.72),
		pixel.V(566.83, 770.70),
		pixel.V(566.24, 770.51),
		pixel.V(565.08, 769.97),
		pixel.V(564.62, 769.75),
		pixel.V(564.36, 769.43),
		pixel.V(564.24, 769.48),
		pixel.V(564.31, 769.64),
		pixel.V(564.55, 769.83),
		pixel.V(565.14, 770.28),
		pixel.V(565.30, 770.47),
		pixel.V(565.30, 770.53),
		pixel.V(565.22, 770.59),
		pixel.V(565.06, 770.55),
		pixel.V(564.87, 770.40),
		pixel.V(564.68, 770.26),
		pixel.V(564.45, 770.24),
		pixel.V(564.25, 770.12),
		pixel.V(564.21, 769.96),
		pixel.V(564.02, 769.65),
		pixel.V(563.99, 769.50),
		pixel.V(563.71, 769.38),
		pixel.V(563.51, 769.30),
		pixel.V(563.55, 769.21),
		pixel.V(563.55, 769.15),
		pixel.V(563.73, 769.17),
		pixel.V(563.87, 769.27),
		pixel.V(563.96, 769.26),
		pixel.V(564.01, 769.15),
		pixel.V(564.01, 769.08),
		pixel.V(564.09, 769.07),
		pixel.V(564.17, 769.15),
		pixel.V(564.38, 769.16),
		pixel.V(564.43, 769.03),
		pixel.V(564.35, 768.77),
		pixel.V(564.42, 768.56),
		pixel.V(564.60, 768.49),
		pixel.V(564.70, 768.36),
		pixel.V(564.75, 768.21),
		pixel.V(564.88, 768.17),
		pixel.V(565.11, 768.09),
		pixel.V(565.16, 767.98),
		pixel.V(565.18, 767.80),
		pixel.V(565.13, 767.53),
		pixel.V(564.98, 767.37),
		pixel.V(564.93, 767.37),
		pixel.V(564.85, 767.47),
		pixel.V(564.86, 767.66),
		pixel.V(564.86, 767.76),
		pixel.V(564.77, 767.80),
		pixel.V(564.67, 767.71),
		pixel.V(564.62, 767.49),
		pixel.V(564.58, 767.41),
		pixel.V(564.50, 767.36),
		pixel.V(564.43, 767.42),
		pixel.V(564.33, 767.52),
		pixel.V(564.24, 767.58),
		pixel.V(564.08, 767.49),
		pixel.V(563.99, 767.29),
		pixel.V(564.04, 767.00),
		pixel.V(563.97, 766.81),
		pixel.V(564.23, 766.53),
		pixel.V(564.25, 766.36),
		pixel.V(564.28, 766.22),
		pixel.V(564.18, 765.88),
		pixel.V(564.18, 765.73),
		pixel.V(564.44, 765.29),
		pixel.V(564.65, 764.92),
		pixel.V(564.79, 764.71),
		pixel.V(565.23, 764.39),
		pixel.V(565.74, 763.95),
		pixel.V(566.61, 763.50),
		pixel.V(567.41, 763.20),
		pixel.V(568.36, 762.65),
		pixel.V(568.93, 762.39),
		pixel.V(569.48, 762.35),
		pixel.V(569.88, 762.25),
		pixel.V(570.09, 762.05),
		pixel.V(570.11, 761.79),
		pixel.V(570.67, 760.76),
		pixel.V(571.26, 759.53),
		pixel.V(571.29, 758.83),
		pixel.V(571.43, 758.40),
		pixel.V(571.64, 758.16),
		pixel.V(572.33, 757.49),
		pixel.V(573.07, 756.95),
		pixel.V(574.05, 756.46),
		pixel.V(574.41, 756.29),
		pixel.V(574.87, 755.88),
		pixel.V(575.41, 755.63),
		pixel.V(575.81, 755.50),
		pixel.V(576.18, 755.27),
		pixel.V(577.74, 754.94),
		pixel.V(578.06, 754.92),
		pixel.V(578.93, 755.03),
		pixel.V(579.86, 755.16),
		pixel.V(580.39, 755.17),
		pixel.V(580.77, 755.06),
		pixel.V(581.02, 754.85),
		pixel.V(581.03, 754.69),
		pixel.V(581.03, 754.42),
		pixel.V(580.63, 754.17),
		pixel.V(580.07, 753.92),
		pixel.V(579.84, 753.70),
		pixel.V(579.78, 753.53),
		pixel.V(579.84, 753.32),
		pixel.V(580.15, 753.09),
		pixel.V(580.76, 752.73),
		pixel.V(581.65, 752.43),
		pixel.V(582.74, 752.08),
		pixel.V(583.83, 751.69),
		pixel.V(584.73, 751.51),
		pixel.V(585.40, 751.23),
		pixel.V(586.29, 750.62),
		pixel.V(586.96, 750.28),
		pixel.V(588.22, 749.80),
		pixel.V(588.84, 749.60),
		pixel.V(589.33, 749.23),
		pixel.V(590.24, 748.46),
		pixel.V(590.61, 748.17),
		pixel.V(590.81, 747.81),
		pixel.V(590.77, 747.35),
		pixel.V(590.57, 746.93),
		pixel.V(590.48, 746.61),
		pixel.V(590.48, 746.40),
		pixel.V(590.55, 746.14),
		pixel.V(590.55, 745.97),
		pixel.V(590.45, 745.89),
		pixel.V(590.09, 745.86),
		pixel.V(589.71, 746.11),
		pixel.V(588.91, 747.00),
		pixel.V(588.36, 747.87),
		pixel.V(588.04, 748.06),
		pixel.V(587.30, 748.13),
		pixel.V(586.09, 748.18),
		pixel.V(585.79, 748.27),
		pixel.V(585.39, 748.76),
		pixel.V(584.95, 749.01),
		pixel.V(584.46, 749.01),
		pixel.V(584.05, 748.78),
		pixel.V(583.68, 748.44),
		pixel.V(583.47, 747.86),
		pixel.V(583.24, 747.61),
		pixel.V(582.84, 747.32),
		pixel.V(582.78, 747.11),
		pixel.V(582.87, 746.65),
		pixel.V(582.84, 746.40),
		pixel.V(582.58, 745.99),
		pixel.V(582.53, 745.71),
		pixel.V(582.71, 745.43),
		pixel.V(582.99, 745.27),
		pixel.V(583.79, 745.19),
		pixel.V(584.03, 745.04),
		pixel.V(584.24, 744.73),
		pixel.V(585.00, 744.47),
		pixel.V(585.29, 744.32),
		pixel.V(585.40, 744.14),
		pixel.V(585.24, 744.00),
		pixel.V(585.06, 743.83),
		pixel.V(584.93, 743.60),
		pixel.V(584.97, 743.26),
		pixel.V(585.29, 742.67),
		pixel.V(585.36, 742.43),
		pixel.V(585.28, 742.22),
		pixel.V(585.01, 742.12),
		pixel.V(584.57, 742.16),
		pixel.V(584.05, 742.18),
		pixel.V(583.60, 742.07),
		pixel.V(583.10, 741.66),
		pixel.V(582.94, 741.17),
		pixel.V(582.91, 740.36),
		pixel.V(582.89, 739.97),
		pixel.V(582.11, 739.47),
		pixel.V(581.30, 738.84),
		pixel.V(581.05, 738.43),
		pixel.V(581.01, 738.23),
		pixel.V(580.28, 737.84),
		pixel.V(579.72, 737.72),
		pixel.V(579.36, 737.78),
		pixel.V(579.11, 738.06),
		pixel.V(579.02, 738.56),
		pixel.V(578.83, 738.87),
		pixel.V(578.84, 739.16),
		pixel.V(579.21, 739.61),
		pixel.V(579.82, 740.05),
		pixel.V(580.13, 740.46),
		pixel.V(580.13, 740.64),
		pixel.V(579.91, 740.84),
		pixel.V(579.88, 741.08),
		pixel.V(579.98, 741.24),
		pixel.V(580.29, 741.31),
		pixel.V(580.88, 741.36),
		pixel.V(581.21, 741.46),
		pixel.V(581.39, 741.75),
		pixel.V(581.22, 742.09),
		pixel.V(580.87, 742.73),
		pixel.V(580.79, 743.30),
		pixel.V(580.80, 743.74),
		pixel.V(580.67, 743.97),
		pixel.V(579.84, 744.81),
		pixel.V(579.56, 745.29),
		pixel.V(579.50, 745.99),
		pixel.V(579.50, 746.35),
		pixel.V(579.14, 746.73),
		pixel.V(578.73, 747.12),
		pixel.V(578.44, 747.15),
		pixel.V(577.81, 747.05),
		pixel.V(577.48, 746.87),
		pixel.V(577.29, 746.88),
		pixel.V(576.95, 747.24),
		pixel.V(576.84, 747.39),
		pixel.V(576.49, 747.56),
		pixel.V(576.01, 747.64),
		pixel.V(575.75, 747.78),
		pixel.V(575.63, 747.94),
		pixel.V(575.88, 748.44),
		pixel.V(575.85, 748.69),
		pixel.V(575.52, 749.21),
		pixel.V(575.29, 749.60),
		pixel.V(575.09, 749.71),
		pixel.V(574.81, 749.72),
		pixel.V(573.76, 749.44),
		pixel.V(573.38, 749.42),
		pixel.V(573.13, 749.37),
		pixel.V(572.97, 749.38),
		pixel.V(572.97, 749.46),
		pixel.V(573.15, 749.61),
		pixel.V(573.40, 749.66),
		pixel.V(573.57, 749.79),
		pixel.V(573.58, 749.99),
		pixel.V(573.35, 750.15),
		pixel.V(572.69, 750.34),
		pixel.V(572.10, 750.37),
		pixel.V(571.91, 750.26),
		pixel.V(571.88, 750.19),
		pixel.V(571.78, 750.17),
		pixel.V(571.78, 750.33),
		pixel.V(571.91, 750.60),
		pixel.V(571.91, 750.78),
		pixel.V(571.73, 750.90),
		pixel.V(571.38, 751.01),
		pixel.V(571.10, 751.58),
		pixel.V(570.85, 751.94),
		pixel.V(570.28, 752.12),
		pixel.V(569.98, 752.13),
		pixel.V(569.92, 752.07),
		pixel.V(569.92, 751.98),
		pixel.V(569.90, 751.87),
		pixel.V(569.78, 751.89),
		pixel.V(569.51, 751.99),
		pixel.V(569.14, 752.22),
		pixel.V(568.95, 752.32),
		pixel.V(568.53, 752.30),
		pixel.V(568.34, 752.22),
		pixel.V(568.04, 752.12),
		pixel.V(567.80, 752.07),
		pixel.V(567.65, 752.13),
		pixel.V(567.61, 752.31),
		pixel.V(567.52, 752.54),
		pixel.V(567.35, 752.68),
		pixel.V(566.63, 752.88),
		pixel.V(566.03, 752.95),
		pixel.V(565.61, 753.08),
		pixel.V(565.44, 753.36),
		pixel.V(565.29, 753.64),
		pixel.V(564.83, 753.84),
		pixel.V(564.25, 754.22),
		pixel.V(563.56, 754.52),
		pixel.V(563.20, 754.68),
		pixel.V(562.97, 754.75),
		pixel.V(562.53, 754.97),
		pixel.V(562.19, 755.25),
		pixel.V(561.86, 755.75),
		pixel.V(561.54, 756.10),
		pixel.V(560.84, 756.49),
		pixel.V(560.55, 756.53),
		pixel.V(560.09, 756.74),
		pixel.V(559.95, 756.75),
		pixel.V(559.85, 756.69),
		pixel.V(559.77, 756.52),
		pixel.V(559.66, 756.50),
		pixel.V(559.40, 756.59),
		pixel.V(559.33, 756.70),
		pixel.V(559.35, 756.77),
		pixel.V(559.59, 756.88),
		pixel.V(559.68, 757.15),
		pixel.V(559.67, 757.24),
		pixel.V(559.59, 757.30),
		pixel.V(559.45, 757.30),
		pixel.V(559.39, 757.34),
		pixel.V(559.31, 757.49),
		pixel.V(558.54, 758.11),
		pixel.V(558.32, 758.17),
		pixel.V(557.98, 758.19),
		pixel.V(557.88, 758.22),
		pixel.V(557.82, 758.26),
		pixel.V(557.88, 758.67),
		pixel.V(557.64, 758.89),
		pixel.V(557.44, 758.96),
		pixel.V(557.26, 758.97),
		pixel.V(556.95, 758.84),
		pixel.V(556.82, 758.85),
		pixel.V(556.68, 758.94),
		pixel.V(556.63, 759.05),
		pixel.V(556.78, 759.34),
		pixel.V(556.92, 759.86),
		pixel.V(556.86, 760.12),
		pixel.V(556.64, 760.55),
		pixel.V(555.84, 761.59),
		pixel.V(555.75, 761.79),
		pixel.V(555.85, 762.48),
		pixel.V(555.74, 762.77),
		pixel.V(555.31, 763.23),
		pixel.V(554.38, 763.67),
		pixel.V(553.89, 763.93),
		pixel.V(553.74, 763.94),
		pixel.V(553.70, 763.92),
		pixel.V(553.76, 763.78),
		pixel.V(553.73, 763.75),
		pixel.V(553.68, 763.75),
		pixel.V(553.55, 763.80),
		pixel.V(553.17, 764.05),
		pixel.V(552.44, 764.38),
		pixel.V(552.22, 764.42),
		pixel.V(552.06, 764.49),
		pixel.V(551.88, 764.62),
		pixel.V(551.77, 764.63),
		pixel.V(551.62, 764.65),
		pixel.V(551.49, 764.74),
		pixel.V(551.42, 764.89),
		pixel.V(551.33, 764.97),
		pixel.V(551.19, 764.96),
		pixel.V(551.10, 764.92),
		pixel.V(551.05, 764.84),
		pixel.V(551.14, 764.63),
		pixel.V(551.13, 764.59),
		pixel.V(551.07, 764.57),
		pixel.V(550.93, 764.60),
		pixel.V(550.41, 764.93),
		pixel.V(549.34, 765.26),
		pixel.V(549.10, 765.27),
		pixel.V(548.91, 765.24),
		pixel.V(548.06, 764.84),
		pixel.V(547.94, 764.81),
		pixel.V(547.90, 764.76),
		pixel.V(547.94, 764.63),
		pixel.V(547.86, 764.31),
		pixel.V(547.57, 764.15),
		pixel.V(547.21, 764.04),
		pixel.V(547.09, 763.97),
		pixel.V(547.05, 763.88),
		pixel.V(547.05, 763.70),
		pixel.V(546.99, 763.60),
		pixel.V(546.83, 763.49),
		pixel.V(546.75, 763.45),
		pixel.V(546.73, 763.30),
		pixel.V(546.62, 763.20),
		pixel.V(546.39, 763.13),
		pixel.V(546.07, 762.94),
		pixel.V(545.47, 762.76),
		pixel.V(545.06, 762.59),
		pixel.V(544.44, 762.58),
		pixel.V(544.10, 762.54),
		pixel.V(544.03, 762.83),
		pixel.V(544.01, 763.09),
		pixel.V(544.16, 763.42),
		pixel.V(544.44, 763.74),
		pixel.V(544.54, 764.02),
		pixel.V(544.54, 764.35),
		pixel.V(544.43, 764.46),
		pixel.V(544.39, 764.46),
		pixel.V(544.34, 764.45),
		pixel.V(543.79, 764.14),
		pixel.V(543.57, 764.12),
		pixel.V(543.30, 764.15),
		pixel.V(542.76, 764.24),
		pixel.V(542.03, 764.42),
		pixel.V(541.59, 764.68),
		pixel.V(541.43, 764.95),
		pixel.V(541.18, 765.23),
		pixel.V(541.30, 765.68),
		pixel.V(541.16, 765.80),
		pixel.V(541.14, 765.85),
		pixel.V(541.14, 765.89),
		pixel.V(541.48, 766.18),
		pixel.V(541.46, 766.44),
		pixel.V(541.43, 766.54),
		pixel.V(541.43, 766.58),
		pixel.V(541.50, 766.64),
		pixel.V(541.89, 766.64),
		pixel.V(541.99, 766.66),
		pixel.V(542.09, 766.71),
		pixel.V(542.11, 766.85),
		pixel.V(541.71, 767.19),
		pixel.V(540.98, 767.36),
		pixel.V(540.71, 767.51),
		pixel.V(540.44, 767.91),
		pixel.V(540.12, 768.06),
		pixel.V(539.92, 768.12),
		pixel.V(539.86, 768.20),
		pixel.V(539.85, 768.28),
		pixel.V(539.91, 768.34),
		pixel.V(540.10, 768.38),
		pixel.V(540.67, 768.43),
		pixel.V(541.29, 768.57),
		pixel.V(542.09, 768.92),
		pixel.V(542.26, 769.07),
		pixel.V(542.39, 769.36),
		pixel.V(542.35, 769.60),
		pixel.V(542.07, 769.92),
		pixel.V(541.15, 770.59),
		pixel.V(541.00, 770.81),
		pixel.V(541.00, 770.98),
		pixel.V(541.09, 771.25),
		pixel.V(541.57, 771.64)}

	imd2 = imdraw.New(nil)
	imd2.Color = colornames.Red
	imd3 = imdraw.New(nil)
	imd3.Color = colornames.Blue
	for _, point := range italie {
		imd2.Push(point)
		imd3.Push(point)
		//imd.Color = pixel.RGB(125, 125, 125)

	}
	imd2.EndShape = imdraw.NoEndShape
	imd3.EndShape = imdraw.NoEndShape

	imd2.Polygon(0)
	imd3.Polygon(1)
	pixelgl.Run(run)
}
`

**Comment by xinkiknix** [comment]
pressing the space-bar switches between the two options

**Comment by xinkiknix** [comment]
https://pastebin.com/kbuu0Tdb
![italie polygone 0](https://user-images.githubusercontent.com/3612760/33092888-c7a2d98a-cefb-11e7-9701-800e2bec5dd9.PNG)
![italie polygone 1](https://user-images.githubusercontent.com/3612760/33092889-c7cb5dec-cefb-11e7-9423-2b294edc2af0.PNG)

**Comment by faiface** [comment]
Okay, yeah, I understand the problem with the second one. It's because of an not-ideal algorithm used to calculate points of a thick polygon, which assumes that the normals are not intersecting. That should be fixed.

Regarding the first picture, what's wrong with that?

(And btw, your paste is private, I can't see it.)

**Comment by faiface** [comment]
Ah, I see what's wrong with the first one. The thing is, that polygon filling is only intended for convex polygons. Concave polygons, like yours can produce unexpected results. This won't change. Drawing concave polygons universally correctly is too complicated and slow to be worth it.

**Comment by xinkiknix** [comment]
Now it is public....

**Comment by xinkiknix** [comment]
How is Triangels supposed to be used?  I managed to split the polygon into triangles, but struggle to send these in one call to the draw function. Is there an example on how to use triangles?

**Comment by faiface** [comment]
So, you have two options.

1. You can still use `imdraw` to draw the triangles. Each triangle as individual polygon. Note, that an OpenGL call occurs only when you draw the `imdraw` to a window and you can do this once after you draw all of the triangles.

2. Use `TrianglesData`, fill them with your data (should be obvious how, just allocate it using `MakeTrianglesData` and fill the vertex properties). Then, you can draw the triangles using a `Drawer` (set it up with a `nil` picture and your triangles, and you're ready to go).

If you have any more questions, feel free to ask.

**Comment by xinkiknix** [comment]
The `imdraw` works, but requires a lot of items to draw, one for each triangle. That was the method used to draw Italy triangles.
The `TrianglesData` works but in a strange way. all triangles seem to originate at the first point of the first triangle giving weird results
This is using IMdraw:
![image](https://user-images.githubusercontent.com/3612760/33434749-7b49cf30-d5e0-11e7-8f3a-c71f6afccefb.png)

This one using Triangles
![image](https://user-images.githubusercontent.com/3612760/33434779-9b242210-d5e0-11e7-8ac6-5020cfb63d62.png)

Using following code:

```
> trianglesdata := *pixel.MakeTrianglesData(len(l))
> 
> 	for i, res := range l {
> 
> 		color := pixel.RGB(r.Float64(), r.Float64(), r.Float64())
> 
> 		theVector := pixel.V(res[0], res[1])
> 
> 		imd.Push(theVector)
> 
> 		imd.Color = color
> 
> 		trianglesdata[i].Position = pixel.V(res[0], res[1])
> 
> 		trianglesdata[i].Color = color
> }
> 	imd.Polygon(0)
> 
> 	drawer := pixel.NewBatch(&trianglesdata, nil)
```

**Comment by xinkiknix** [comment]
Programming error from my side ....

**Comment by faiface** [comment]
@aurbano AFAIK, concave polygon triangulation is a pretty hard and non-linear (i.e. slow) problem. Correct me if I'm wrong. That's why I haven't included it in Pixel. Actually, I've struggled for quite a long time to make IMDraw line-drawing not overlap triangles under any circumstances and failed to do it. So, I can't recommend any general way of drawing concave polygons, however, most cases don't involve anything general. Usually you're only dealing with a well-defined set of concave polygons that you can figure out how to draw.

**Comment by aurbano** [comment]
@faiface hmm fair enough - I've just forked a triangulation implementation (of the Ear clipping algo), which is pretty slow but should be good for my needs.

I'm using pixel to render a track for a self-driving car framework, and the track is only generated once in a while, so speed is no issue:

![screen shot 2018-05-30 at 16 43 59](https://user-images.githubusercontent.com/2827818/40731370-c6aaf306-6428-11e8-9a46-328f1cf219f0.png)

Tracks are random, and will eventually get more complex (for now I'm just using a convex hull and then adding some displacement points to make concave turns as well)

(In this sample the car has driven off-track haha, the orange lines are its sensors btw)

**Comment by faiface** [comment]
@aurbano That looks like an awesome project! Feel free to share on our Gitter when you feel like it!

**Comment by xinkiknix** [comment]
I managed to do triangulation for concave shapes, it manages like 38391 triangles in 526ms processing time,  or 1023750 triangles 10sec processing time (8 cores). It is pretty fast for most shapes, but as not all shapes are easy, some are non-deterministic, the process will try a given number of loops.  Small shapes are calculated and shown in a fraction of a second. I can share the code if you are interested.

**Comment by aurbano** [comment]
@xinkiknix sounds really good :) could you share your code?

**Comment by xinkiknix** [comment]
Please find the source at https://github.com/xinkiknix/Go-Triangulation for a working example. The default SHP used in the map is very detailed and thus takes some time to process.
Michal feel free to use in examples :-)
