### ISSUE TITLE
Outlining triangles 

### ISSUE THREAD

**Issue by Jumziey** [faiface/pixel#72]
I've written up a test using this framework. I implement the Triangles interface and some of TriangleData in order to write out triangles i just define by hands. The result as pictured

![triangles](https://user-images.githubusercontent.com/2522611/33230261-421f1af2-d1e0-11e7-815d-51a21e5b2619.png)

Question is if there's an easy way to make outlines to these triangles so one can see the underlying mesh? I've poked around a bit and haven't found a clear way of doing this. The best way i've comed up with is wrapping lots of draw calls for seperate triangles to one batch. Maybe this is the best way of doing things?

Here's the code for reference:
```go
package main

import (
	"github.com/faiface/pixel"
	"github.com/faiface/pixel/pixelgl"
	"golang.org/x/image/colornames"
)

type visual struct {
	vertices []pixel.Vec
	color    pixel.RGBA
}

func (v *visual) Len() int {
	return len(v.vertices)
}

func (v *visual) SetLen(len int) {
	v.vertices = v.vertices[:len]
}

func (v *visual) Slice(i, j int) pixel.Triangles {
	return &visual{vertices: v.vertices[i:j]}
}

func (v *visual) Update(t pixel.Triangles) {
	//nothing
}

func (v *visual) Copy() pixel.Triangles {
	newV := make([]pixel.Vec, len(v.vertices))
	copy(newV, v.vertices)
	return &visual{vertices: newV}
}

func (v *visual) Color(i int) pixel.RGBA {
	return v.color
}

func (v *visual) Position(i int) pixel.Vec {
	return v.vertices[i]
}

func run() {
	cfg := pixelgl.WindowConfig{
		Title:  "Aboat!",
		Bounds: pixel.R(0, 0, 1024, 768),
	}

	win, err := pixelgl.NewWindow(cfg)
	if err != nil {
		panic(err)
	}

	v := visual{
		vertices: []pixel.Vec{
			pixel.V(200, 100),
			pixel.V(800, 100),
			pixel.V(500, 700),
			pixel.V(0, 700),
			pixel.V(200, 100),
			pixel.V(500, 700),
		},
		color: pixel.RGBA{0, 1, 10000, 0},
	}

	batch := pixel.NewBatch(&v, nil)

	win.Clear(colornames.Forestgreen)
	for !win.Closed() {
		win.Clear(colornames.Forestgreen)
		batch.Draw(win)
		win.Update()
	}
}

func main() {
	pixelgl.Run(run)
}
```

**Comment by faiface** [comment]
Hi! Pixel can only draw triangles, so in order to draw lines, you need to compose them out of triangles.

But, that functionality is already implemented in the `"github.com/faiface/pixel/imdraw"` package. Have you tried that?

**Comment by Jumziey** [comment]
Yeah, that's basically what i've done in order to draw the outlines. This should however be doable by setting the polygonmode in opengl to line instead of fill. Maybe i could even look into it in the future for a PR if it's feasible in this framework, and given it's intressting enough... but right now i suspect i'll go with the imdraw package

Ty for quick response :)

**Comment by faiface** [comment]
A really good reason would be required for supporting other modes in OpenGL, that simple triangles. The reason is simplicity and a nice abstraction I get when only supporting triangles. Plus, it seems sufficient. Drawing a line using two triangles is actually really fast.
