### ISSUE TITLE
Is drawing "threadsafe"?

### ISSUE THREAD

**Issue by quillaja** [faiface/pixel#76]
Let's say I have a lot of sprites to draw. In your (very good) tutorial, you discuss the use of `Batch` to help speed up the drawing process. I'm curious about the possibility of using multiple goroutines to split up the drawing of a sprite to batch multiple times, for example in a worker pool type scenario. 

Is there any reason I'd have weird thread/race condition related problems drawing in these scenarios?
1. a single sprite to a single batch (as below)
2. a single sprite to multiple batches
3. multiple sprites to a single batch
4. multiple sprites to multiple batches

I've included a rough code example for clarity. Thanks!

```golang
func worker(sprite pixel.Sprite, batch *pixel.Batch, 
            jobs <-chan []pixel.Vec, done chan<- bool) {
	for points := range jobs {
		for _, p := range points {
			sprite.Draw(batch, pixel.IM.Moved(p))
		}
		done <- true
	}
}

func loop() {

	// ignore instantiation for example
	var mySprite pixel.Sprite
	var myBatch *pixel.Batch
	var myHugeSliceOfEntityPositions []pixel.Vec

	var in chan []pixel.Vec
	var out chan bool

	// make workers
	numGroups := 2
	for w := 0; w < numGroups; w++ {
		go worker(mySprite, myBatch, in, out)
	}

	// do other stuff...
	// then start draw loop

	for !win.Closed() {

		myBatch.Clear()

		// divide and conquer when drawing updated entity state
		half := len(myHugeSliceOfEntityPositions) / numGroups
		in <- myHugeSliceOfEntityPositions[:half]
		in <- myHugeSliceOfEntityPositions[half:]

		// wait for workers
		for w := 0; w < numGroups; w++ {
			<-out
		}

		// draw to window
		myBatch.Draw(win)
		win.Update()
	}
}
```

**Comment by faiface** [comment]
The rule for concurrency safety in Pixel is as follows:

Dealing concurrently with two **separate** objects is **always fine**.

Dealing concurrently with a **single** object is **never fine**.

Following this rule, we can answer your question. Concurrently drawing one sprite to one batch is a race condition. Two separate sprites to one batch is too. Two sprites to two separate baches is fine. One sprite to two separate batches *should* be fine too, although it violates the rule (but we are only reading from the sprite).

**Comment by quillaja** [comment]
Awesome! Thank you for the quick reply!
