### ISSUE TITLE
Provide API for polling window events without redrawing the screen

### ISSUE THREAD

**Issue by mewmew** [faiface/pixel#78]
My friends and I have been playing around with integrating Pixel in a game, and we would like to be able to poll for window events without having to redraw the screen.

In our use case, we don't control when when rendering happens as we integrate Pixel into an already existing game engine. We'd still like to poll window events to forward actions triggered by mouse and keyboard events to the game engine.

Locally, we've been using the following patch. If there is a better way to do it, I'd definitely be happy to discuss alternatives. Also, if the design decision is to keep the Pixel API minimal, I understand if you'd wish not to apply this change and expose more of the API. If so, we can continue to use this patch locally.

```diff
diff --git a/pixelgl/input.go b/pixelgl/input.go
index ff98805..2bbb3a4 100644
--- a/pixelgl/input.go
+++ b/pixelgl/input.go
@@ -372,7 +372,7 @@ func (w *Window) initInput() {
        })
 }
 
-func (w *Window) updateInput() {
+func (w *Window) UpdateInput() {
        mainthread.Call(func() {
                glfw.PollEvents()
        })
diff --git a/pixelgl/window.go b/pixelgl/window.go
index 26d96f7..3716574 100644
--- a/pixelgl/window.go
+++ b/pixelgl/window.go
@@ -192,7 +192,7 @@ func (w *Window) Update() {
                w.end()
        })
 
-       w.updateInput()
+       w.UpdateInput()
 }
 
 // SetClosed sets the closed flag of the Window.
@@ -244,6 +244,7 @@ func (w *Window) SetPos(pos pixel.Vec) {
                w.window.SetPos(left, top)
        })
 }
+
 // Bounds returns the current bounds of the Window.
 func (w *Window) Bounds() pixel.Rect {
        return w.bounds
```

Cheers,
/u & i

**Comment by faiface** [comment]
Okay, this is not so bad of an addition. If you make a PR, I'll accept it. Of course, documentation of the `Window.UpdateInput` method is needed to be added.
