### ISSUE TITLE
Textures in IM 

### ISSUE THREAD

**Issue by svera** [faiface/pixel#81]
I was trying to create a rectangle using immediate mode and fill it with a texture, but I discovered that, when using the `Picture` property, you don't specify a region of the texture to render inside the rectangle, but just a single vector, which in fact just applies the specific pixel color of the texture at those coordinates to the whole rectangle.
Am I missing something? How can I fill a rectangle with a texture in IM?

**Comment by faiface** [comment]
Try assigning different Picture vector values to different points of a rectangle or a polygon ;)

**Comment by svera** [comment]
@faiface that's what I finally did, but is that the way is meant to be used? Because filling a polygon pixel by pixel seems painfully slow.

**Comment by faiface** [comment]
Yeah, that's how it's supposed to be. And well, you're not filling it pixel by pixel but vertex by vertex. Rest of the pixels get interpolated.

But, if your "picturing" of a polygon is not entirely arbitrary, you can always make yourself an own function that automates this process.

**Comment by svera** [comment]
> you're not filling it pixel by pixel but vertex by vertex. Rest of the pixels get interpolated.

@faiface ok, now I understand. IMHO, this doesn't get clear from the examples and docs as far as I've read, so maybe I'll make a PR about it.
Thank you for your quick answer, really appreciated!
