### ISSUE TITLE
Add cursor hiding

### ISSUE THREAD

**Issue by faiface** [faiface/pixel#9]
Add two `*pixelgl.Window` methods:
- `(*pixelgl.Window).SetCursorVisible(bool)` - sets the visibility of the mouse cursor inside the window client area
- `(*pixelgl.Window).CursorVisible() bool` - returns the visibility status of the mouse cursor

**Comment by faiface** [comment]
Tested that #13 works correctly.

**Comment by chaseisabelle** [comment]
I am having issues hiding the cursor. I've attached a little of my code. Perhaps I'm doing something wrong?

```
func run() {
	monitor := pixelgl.PrimaryMonitor()
	width, height := monitor.Size()

	cfg := pixelgl.WindowConfig{
		Bounds: pixel.R(0, 0, width, height),
		VSync:  true,
		Undecorated: true,
		Resizable: false,
	}

	win, err := pixelgl.NewWindow(cfg)

	if err != nil {
		panic(err)
	}

	win.SetMonitor(monitor) //<< fullscreen
	win.SetCursorVisible(false)

	imd := imdraw.New(nil)
	rect := pixel.R(100, 100, 200, 300)

	for !win.Closed() {
		win.Clear(colornames.Beige)
		imd.Clear()

		mouse := win.MousePosition()
		rect = rect.Moved(rect.Center().To(mouse)) //<< move rect to mouse pos

		// draw the rect
		imd.Color = color.Black
		imd.Push(rect.Min, rect.Max)
		imd.Rectangle(3)

		imd.Draw(win)
		win.Update()
	}
}
```

**Comment by bcvery1** [comment]
"issues hiding the cursor", what issues?  I've run your code and it is working fine

Do you have any errors in the terminal?

**Comment by chaseisabelle** [comment]
The code runs fine, no errors/warnings. The cursor is actually hidden during a screenshot, so I had to go old school: https://youtu.be/UT4wIvwlgZU

**Comment by faiface** [comment]
@chaseisabelle You say the cursor is hidden during the screenshot... isn't that good? What's wrong with your code? What is it doing that you're not expecting?

**Comment by chaseisabelle** [comment]
It is hidden during the screenshot, yea, but I'm trying to hide it during the display time also. It sounds like it's a bug specific to my environment. I will dig in and see if I can fix it; if so, I'll submit a PR. Thanks, @faiface !
