### ISSUE TITLE
Example of Implementing a HUD

### ISSUE THREAD

**Issue by peteclark-io** [faiface/pixel#91]
Hello, 

I'm (_very_) new to game development, but have ambitiously decided to make my first game using Pixel. The game will basically be a board game; with a player HUD keeping score etc., and a map which can be navigated, and zoomed in and out.

My question is, how would you suggest I implement the HUD? There's plenty of examples of drawing to a Canvas in the "game space" (incl. camera position), which I believe would be my map, and plenty of examples of drawing text to screen, which could make up my HUD, but how do I combine the two in a sane way?

Any tips would be much appreciated.

P

**Comment by faiface** [comment]
Hi!

Your problem can be solved in two ways.

1. You can draw the whole map/scene with one matrix (camera), then on top of that draw the HUD with another matrix (probably identity matrix = no transformation).
2. You can draw the map to one canvas, the HUD to another canvas and then draw these canvases in the correct order to the window.

**Comment by peteclark-io** [comment]
That's great! Thanks, I took option 2
