### ISSUE TITLE
Control on which monitor the window will pop up

### ISSUE THREAD

**Issue by sharpner** [faiface/pixel#92]
hi!

Is there any way to control on which monitor the windowed application will pop up?

When I set Window in the Window Config to nil, the application will start on my primary window. Changing this setting to a monitor, will result in the application launching on my target monitor, but in fullscreen. 

So I would love to control the monitor, but for a windowed application, is that possible?

Thanks in advance

**Comment by faiface** [comment]
Hi! Yeah, this is not possible and if I understand correctly, it's not even possible in GLFW (http://www.glfw.org/), which is the library we use under the hood for windowing. I'm not sure it's even a good idea to support it at all, as I feel like it should be the window manager's responsibility to place windows on monitors.

Hope this answered your question :)

**Comment by sharpner** [comment]
thanks :) okay yes that answers my question, thanks for the fast response!
