### ISSUE TITLE
Svg sprites?

### ISSUE THREAD

**Issue by xahon** [faiface/pixel#94]
I didn't see in tutorial any mentioning about svg graphics. Is this possible?

**Comment by faiface** [comment]
Hi, Pixel has no built-in support for SVG graphics. In fact, Pixel has no built-in support for any graphics format. Anything that you can turn into an `image.Image` type from the standard library works. I'm not aware of any Go library for decoding SVGs into `image.Image`, so you'll probably just need to convert it to PNG or something.

**Comment by faiface** [comment]
Did you find the answer satisfying?

**Comment by xahon** [comment]
@faiface no, I didn't search

**Comment by delp** [comment]
There doesn't appear to be a package in golang (yet) for converting SVG to image.image.

**Comment by Noofbiz** [comment]
https://github.com/srwiley/oksvg is able to do that
