### ISSUE TITLE
Rect.Ressized does not work as documented

### ISSUE THREAD

**Issue by ptriller** [faiface/pixel#98]
As far as I understand the documentation on the mehtod Rect.Resized, it does not work as advertized. 
I wrote a small test to replicate

When using `rect.Max` as anchor, The`result.Max` should be the same als the `rect.Max`, but it is not.

```
package main

import (
	"github.com/faiface/pixel"
	"testing"
	"reflect"
)

func TestResize(t *testing.T) {
	rect := pixel.R(0,0,100,100)
	result := rect.Resized(rect.Max, pixel.V(100, 90))
	if !reflect.DeepEqual(result, pixel.R(0,10,100,100)) {
		t.Error("Result not as expected")
	}
}
```

**Comment by faiface** [comment]
Interestingly, `reflect.DeepEqual` returns `true` for me. I believe this has something to do with floating-point calculation. `rect.Resized` does not guarantee a perfect equality, the formula it uses is correct, but floating-point calculations can introduce minor imprecisions.

**Comment by ptriller** [comment]
Weird, I will test again under a different setup.

**Comment by faiface** [comment]
Have you tested again?

**Comment by ptriller** [comment]
Yes, on my second machine it worked at once. On my other machine it still did not work, but it started working after I deleted all workspace files of go . If anything it is a bug in the caching of the go compiler or some other weirdness
